### DISCUSSION TITLE
using azurefile-csi-driver in k3d

### DISCUSSION THREAD

**Discussion by bartr** [kubernetes-sigs/azurefile-csi-driver#1001] [Q&A] [answered]
I'm following the instructions here: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-pvpvc 

I have a clean k3d cluster and I'm able to mount my azure file share from the host and the node. Should this work? I've tried all of the different methods on that page and get the same error.

Everything looks good but when I deploy the nginx app (or any app) that uses the PVC, the pod hangs in creating. After a couple of minutes, I get the following errrors:

```text

Type     Reason              Age   From                     Message
  ----     ------              ----  ----                     -------
  Normal   Scheduled           3m5s  default-scheduler        Successfully assigned default/nginx-azurefile to k3d-k3s-default-server-0
  Warning  FailedMount         63s   kubelet                  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage kube-api-access-4pdh5]: timed out waiting for the condition
  Warning  FailedAttachVolume  27s   attachdetach-controller  AttachVolume.Attach failed for volume "pv-azurefile" : Attach timeout for volume upload-volumeid

```

Here's my PV/PVC yaml

```yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  # https://linux.die.net/man/8/mount.cifs
    - nosharesock
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: upload-volumeid
    volumeAttributes:
      shareName: uploadvolume
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi

```

k describe pvc pvc-azure output

```text

Name:          pvc-azurefile
Namespace:     default
StorageClass:  azurefile-csi
Status:        Bound
Volume:        pv-azurefile
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      10Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       nginx-azurefile
Events:        <none>

```
