### DISCUSSION TITLE
How to initialise csi volume with driver "file.csi.azure.com" using java SDK

### DISCUSSION THREAD

**Discussion by itsmylife-yo** [kubernetes-sigs/azurefile-csi-driver#1122] [Q&A]
I want to effectively add this snippet of manifest using kubernetes java SDK. Can someone please help? 

```
volumes:
        - name: mydrivename
          csi:
            driver: file.csi.azure.com
            readOnly: false
            volumeAttributes:
              secretName: secret
              shareName: sharedId
```
