### DISCUSSION TITLE
High CPU usage of java application when mounting file share into pod

### DISCUSSION THREAD

**Discussion by HerrDerb** [kubernetes-sigs/azurefile-csi-driver#1458] [Q&A] [answered]
We mount a file share into a pod running a java application.
```
      volumes:
      - name: "my-storage"
        csi:
          driver: file.csi.azure.com
          readOnly: false
          volumeAttributes:
            secretName: storage-acccount-name-secret
            shareName: storage-ingestion-buffer
```
We get access and can work with the files. But either native or jvm, both results in the same issue.

We experience an increase of CPU usage until lots of files on the file share are getting deleted by another application that mounts the same fileshare.
![image](https://github.com/kubernetes-sigs/azurefile-csi-driver/assets/7398256/91b4acc1-bf1e-4fa9-83f6-ae5491fcf228)

Can it be that this is cause by a kind of caching? We experience this in every application in which we mount a file share over the csi driver.

**Comment by andyzhangx** [comment]
@HerrDerb does the graph shows the cpu usage of azure file driver controller or your application? if you are on AKS, the azure file driver controller is not visible to the user.

**Reply by HerrDerb** [reply]
@andyzhangx No, the graph actually does not say very much, it is from one of the applications that uses the file share. Yes we are on AKS. A you see I don't have any mount options at the moment. We did try:
```
volumeAttributes:
            mountOptions: "cache=nocache"
            secretName: storage-acccount-name-secret
            shareName: storage-ingestion-buffer
```
with the hope, that is might be a problem with the caching mechanism, which we don't need for out application. Id did show no effect. Can you confirm that with this configuration it shoud apply the cach property to the csi driver?
