### ISSUE TITLE
Mounting NFS share gives 403 AuthorizationFailed when 

### ISSUE THREAD

**Issue by sunkararp** [kubernetes-sigs/azurefile-csi-driver#1057]
Hi @andyzhangx 

We followed your [nfs doc](https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/nfs)

**What happened**: Received 403 AuthorizationFailed error when mounting Azure NFS file share

**What you expected to happen**: We should be able to mount the Azure Storage Account NFS share in Linux pod

**How to reproduce it**:

Below is our storageclass-azurefile-nfs.yaml file
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS
  resourceGroup: ***REDACTED ***
  storageAccount: ***REDACTED***
  shareName: sparkdata 
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nconnect=8 
```

Below is PVC file
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 500Gi
```

Below is our StatefulSet relevant portions 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-cluster-worker

          volumeMounts:
            - mountPath: /mount/stprodsparkbewus2/sparkdata
              name: spark-data

volumes:
        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-data-nfs-pvc
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
