### ISSUE TITLE
Require Infrastructure Encryption for Dynamic Storage Class when creating AzureFile CSI

### ISSUE THREAD

**Issue by kpkool** [kubernetes-sigs/azurefile-csi-driver#1064]
**Is your feature request related to a problem?/Why is this needed**

Currently, I am unable to dynamically create storage class (provision/create storage account ) file share with Infrastructure Encryption. I need additional parameters in CSI Driver where I can enable infrastructure encryption either using Microsoft-managed keys or customer-managed keys

**Describe the solution you'd like in detail**

I need additional parameters in CSI Driver where I can enable infrastructure encryption either using Microsoft-managed keys or customer-managed keys

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by andyzhangx** [comment]
hi @kpkool what do you mean by `infrastructure encryption`? do you mean creating a storage account with customer-managed key by the driver? currently the storage account created by the driver is already using Microsoft-managed key already by default, we don't support creating new account with ustomer-managed key now, the workaround is bring your own storage account in storage class, set as `storageAccount: xxx` in storage class:

![image](https://user-images.githubusercontent.com/4178417/182502686-83ddb62b-80db-4883-a6b8-41b672ebcff5.png)

**Comment by kpkool** [comment]
@andyzhangx , yes, creating storage accounts with customer-managed key. Most enterprises and any client with regulatory requirements must have customer-managed keys.  We are hosting workload/app in the multi-tenancy AKS environment. 

Regardless, I think the issue is that "Infrastructure encryption" is still disabled by default as shown above in the screenshot even default option "Microsoft managed keys" is selected.

**Comment by andyzhangx** [comment]
@kpkool thanks, I see, this is another setting, we will fix it in next release.
As a workaround, pls create a storage account with “infrastructure encryption” enabled , and specify storageAccount parameter in azure file storage class:
```yaml
              apiVersion: storage.k8s.io/v1
              kind: StorageClass
              metadata:
                name: azurefile-csi
              provisioner: file.csi.azure.com
              parameters:
                resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as agent node
                storageAccount: EXISTING_STORAGE_ACCOUNT_NAME

```
