### ISSUE TITLE
SubscriptionID parameter not working

### ISSUE THREAD

**Issue by chrosim** [kubernetes-sigs/azurefile-csi-driver#1066]
Version: 1.20.0

Hi we have an AKS Cluster deployed in Subscription "B" with Resource Group "B_AKS"
We want to Mount azurefiles from Subscription "A" with Resource Group "A_Base"
The storageAccount is named "BaseStorage"
The AKS-SP-Identity is assigned as Contributer to ResourceGroup "A_Base" in subscription "A"

When setting the storage-class paramters like:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: baserg-azurefile-csi  
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  subscriptionID: A
  resourceGroup: A_Base
  storageAccount: BaseStorage
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

The provisioning fails with a message saying unauthorized or invalid scope:
...does not have authorization to perform action 'Microsoft.Storage/storageAccounts/fileServices/shares/read' over scope '/subscriptions/B/resourceGroups/A_Base/providers/Microsoft.Storage/storageAccounts/BaseStorage/fileServices/default/shares/pvc-b5511b84-9f65-451f-9a88-43787dcdc478' or the scope is invalid

As you can see the requested subscription is ***B*** and not A
Is this a bug or are we doing something wrong?

**Comment by andyzhangx** [comment]
could you add `useDataPlaneAPI: "true"` in storage class like this:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: baserg-azurefile-csi  
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  subscriptionID: A
  resourceGroup: A_Base
  storageAccount: BaseStorage
  useDataPlaneAPI: "true"
```

if it still fails, pls provide full logs of csi controller, thanks.
