### ISSUE TITLE
Unable to mount Azure File Share as inline volume

### ISSUE THREAD

**Issue by ejschoen** [kubernetes-sigs/azurefile-csi-driver#1078]
**What happened**:
Following instructions from this page: https://docs.microsoft.com/en-us/azure/aks/azure-files-volume 
Pods will not init because of Mount.Setup failures.  

kubectl describe says:
```
MountVolume.SetUp failed for volume "elided" : rpc error: code = InvalidArgument desc = failed to get account name from csi-d08c45243d7cf6b57eb37e8432ba6327930301019e89b1a80bd7e329ee988a6a
```
Kubelet log says:
```
Sep 04 01:17:14 aks-nodepool1-51635614-vmss000008 kubelet[3426]: E0904 01:17:14.767450    3426 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/af8c4ef0-015b-42d6-8b4f-6ff47556966e-elided podName:af8c4ef0-015b-42d6-8b4f-xxxxxxxxxxxx nodeName:}" failed. No retries permitted until 2022-09-04 01:17:46.767423942 +0000 UTC m=+3146510.790991837 (durationBeforeRetry 32s). Error: MountVolume.SetUp failed for volume "elided" (UniqueName: "kubernetes.io/csi/af8c4ef0-015b-42d6-8b4f-6ff47556966e-elided") pod "i2ksource-768d59c487-rq7zj" (UID: "af8c4ef0-015b-42d6-8b4f-6ff47556966e") : rpc error: code = InvalidArgument desc = failed to get account name from csi-51e5b168c4c31742f07e9aacd5c8be54e7728bf284fa9fa158ce6e031f750934 
```

**What you expected to happen**:
Expected Azure file share to mount into 3 pods that request it.

**How to reproduce it**:
Add this to volumes array in PodSpec:
```
      volumes:
      - csi:
          driver: file.csi.azure.com
          readOnly: false
          volumeAttributes:
            secretName: mysecret-1
            shareName: elided
        name: myvolname
```
Create this secret:
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysecret-1
data:
  azurestorageaccountkey:   ---it's a secret---
  azurestorageaccountname: mystorageaccountname
```

**Anything else we need to know?**:
I have tried multiple permutations of options:

1. Tried readOnly both false and true (didn't expect a difference, but the docs show readOnly=false).
2. Tried supplying mountOptions for when readOnly is true to set file and dir mode to 0755
3. Tried adding resourceGroup to volumeAttributes, in case it mattered, since it does for PV mode.
4. Tried with the share in a different resource group and in the same resource group as the cluster.
5. Did confirm that the share is accessible by running nc to the storage-account-name.file.core.windows.net port 445.
6. Cluster is in Central US and storage is in West US. Is this an issue?

**Environment**:

- CSI Driver version: image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.20.0
- Kubernetes version (use `kubectl version`): 1.22.6
- OS (e.g. from /etc/os-release):  Node is Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): Linux aks-nodepool1-51635614-vmss000008 5.4.0-1083-azure #87~18.04.1-Ubuntu SMP Fri Jun 3 13:19:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
