### ISSUE TITLE
Failed to create PersistentVolumeClaims

### ISSUE THREAD

**Issue by mauriciocirelli** [kubernetes-sigs/azurefile-csi-driver#1090]
**What happened**:

We deployed some PVs using azure file shares (nfs) and they were working properly. We are using the same share for all volumes we need in this cluster, using a StorageClass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-default
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  subscriptionID: my-subscription
  resourceGroup: my-resource-group
  storageAccount: my-storage-account
  shareName: my-share-name
  protocol: nfs
  secretNamespace: my-secret-namespace
  secretName: my-secret-name
  folderName: my-folder
```

Later, we needed to increase the share size to accomodate new applications. We went to azure portal and increased the share size there. Then, we tried to deploy new PVCs and they are failing with the following error:

**ContainerQuotaDowngradeNotAllowed**: Cannot downgrade quota at this moment. Please check share properties for the next allowed quota downgrade time.

It is very confusing. We are not trying to downgrade anything. We are just trying to create new volumes in that share. We have tried to stop and start the AKS cluster, but nothing changed.

**What you expected to happen**:

The PVCs and PVs to be created normally.

**How to reproduce it**:

Not sure. It is happening for any size of volume we are trying to create since we had to resize the share.

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.21.0
- Kubernetes version (use `kubectl version`): 1.24.3
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): AKSUbuntu-1804gen2containerd-2022.08.29
- Install tools:
- Others:
