### ISSUE TITLE
it is just a quesiton.what is advantage of csi azure nfs over nfs endpoints directly?

### ISSUE THREAD

**Issue by zffocussss** [kubernetes-sigs/azurefile-csi-driver#1095]
if using nfs server directly.it is simple.
```
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: busybox
    command: ["/bin/sh", "-ec", "sleep 1000"]
    volumeMounts:
      - name: nfs
        mountPath: /var/nfs
  volumes:
  - name: nfs
    nfs:
      server: {existing-fileshare}.file.core.windows.net
```
if using csi nfs file share,it is more complex
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  protocol: nfs
  skuName: Premium_LRS
  resourceGroup: {resourcegroup} # optional, only set this when storage account is not in the same resource group as agent node
  storageAccount: {storageaccount}
  shareName: {sharename}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nconnect=8
#   - dir_mode=0777
#   - file_mode=0777
#   - uid=0
#   - gid=0
#   - mfsymlinks
#   - cache=strict # https://linux.die.net/man/8/mount.cifs
#   - nosharesock # reduce probability of reconnect race
#   - actimeo=30 # reduce latency for metadata-heavy workload
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi-nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azurefile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azurefile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: deployment-azurefile
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
          volumeMounts:
            - name: azurefile
              mountPath: "/mnt/azurefile"
              readOnly: false
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: pvc-azurefile
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

```
