### ISSUE TITLE
Provisioning failed: failed to ensure storage account: Failed to create private DNS zone: no such host

### ISSUE THREAD

**Issue by Mik4sa** [kubernetes-sigs/azurefile-csi-driver#1099]
I hope this is the right place to ask for.

**What happened**:
Starting some time ago no persisted volumes for newly created claims are created. Running `kubectl describe` on that pvc returns the following:
```
Name:          ***
Namespace:     ***
StorageClass:  ***
Status:        Pending
Volume:
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: ***
               meta.helm.sh/release-namespace: ***
               volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       ***
Events:
  Type     Reason                Age               From                                                                                               Message
  ----     ------                ----              ----                                                                                               -------
  Normal   Provisioning          51s               file.csi.azure.com_csi-azurefile-controller-54689c974c-nsglt_3b5de8f8-7450-4802-a06b-ac6c861983cf  External provisioner is provisioning volume for claim "***"
  Normal   ExternalProvisioning  8s (x4 over 51s)  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
  Warning  ProvisioningFailed    1s                file.csi.azure.com_csi-azurefile-controller-54689c974c-nsglt_3b5de8f8-7450-4802-a06b-ac6c861983cf  failed to provision volume with StorageClass "***": rpc error: code = Internal desc = failed to ensure storage account: Failed to create private DNS zone(privatelink.file.core.windows.net) in resourceGroup(***), error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Get "http://germanywestcentral.localhost:7788/subscriptions/***/resourceGroups/***/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net?api-version=2018-09-01": dial tcp: lookup germanywestcentral.localhost on 172.30.0.10:53: no such host
```

I'm not really sure which host is not found or where to find more information.

**What you expected to happen**:
The pv should be created without any errors.

**How to reproduce it**:
My storage class looks like:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ***
mountOptions:
- nconnect=8
parameters:
  enableLargeFileShares: "true"
  networkEndpointType: privateEndpoint
  protocol: nfs
  storageAccountType: Premium_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

and the pvc looks like:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ***
  namespace: ***
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ***
```

**Anything else we need to know?**:
- My nodepools run with `
AKSUbuntu-1804gen2containerd-2022.09.05`
- I'm using the managed CSI driver on AKS

**Environment**:
- CSI Driver version: `image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.21.0`
- Kubernetes version (use `kubectl version`):
  ```
  clientVersion:
    buildDate: "2022-01-19T17:33:06Z"
    compiler: gc
    gitCommit: f59f5c2fda36e4036b49ec027e556a15456108f0
    gitTreeState: clean
    gitVersion: v1.22.6
    goVersion: go1.16.12
    major: "1"
    minor: "22"
    platform: windows/amd64
  serverVersion:
    buildDate: "2022-07-28T23:33:17Z"
    compiler: gc
    gitCommit: ece9ecf2f9aecbd86d3eba31f0be62e4b6353a5a
    gitTreeState: clean
    gitVersion: v1.22.6
    goVersion: go1.16.12
    major: "1"
    minor: "22"
    platform: linux/amd64
  ```
- OS (e.g. from /etc/os-release): `Windows 21H2 (Build 22000.1042)`
- Kernel (e.g. `uname -a`): `-`
- Install tools: `-`
- Others: `-`
