### ISSUE TITLE
Add support for SMB Multi-channels in premium account creation by the driver

### ISSUE THREAD

**Issue by LaurentLesle** [kubernetes-sigs/azurefile-csi-driver#1103]
**Is your feature request related to a problem?/Why is this needed**

Azure file share can be created with SMB multi-channel enabled. [https://learn.microsoft.com/en-us/azure/storage/files/files-smb-protocol?tabs=azure-portal#smb-multichannel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fstorage%2Ffiles%2Ffiles-smb-protocol%3Ftabs%3Dazure-portal%23smb-multichannel&data=05%7C01%7CLaurent.Lesle%40microsoft.com%7C9d1c3ad353cb42e16da508daa67b5813%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638005345969651767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RB4GJDa9OWqdOLOIEMjSGTXwAQB4xyDxYwKrAVcaPXo%3D&reserved=0)

This results in the following benefits for multi-threaded applications:

- Increased throughput
- Increased IOPS
- Network fault tolerance

When mounting the file share the CIFS client must be configured with the number of channel to configure (max 4). Mount option "max_channels=2" (or 3 or 4) can be used to enable multichannel on Linux.

**Describe the solution you'd like in detail**

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/largeFileShares/storageclass-azurefile-largefileshares.yaml

```yaml---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-largefileshares
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_LRS  # available values: Premium_LRS, Premium_ZRS, Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Standard_RAGZRS
  enableLargeFileShares: "true"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
  - max_channels=2 # (or 3 or 4)
```

**Describe alternatives you've considered**

**Additional context**

https://wiki.samba.org/index.php/LinuxCIFSKernel
