### ISSUE TITLE
Attach to volume on external Storage Account from two clusters

### ISSUE THREAD

**Issue by slawekww** [kubernetes-sigs/azurefile-csi-driver#1184]
**What happened**:
Applications on two different clusters want to use the same volume.
Volume is created using StorageClass pointing to external Storage Account using **provisioner: file.csi.azure.com**.
Backup app manifests, pvc and pv manifests on source cluster.
Created the same manifests for pv, pvc and app on target cluster.

Got error on target cluster:
```
$ kubectl get pvc -n test
task-pv-claim-test   Lost     pvc-1e9d0be0-15d4-4743-a357-3fcb69570380   0                         azurefile-backup

$ kubectl describe pvc -n test
...
  Warning  ClaimMisbound  3s    persistentvolume-controller  Two claims are bound to the same volume, this one is bound incorrectly
```

Note: No problems to access external Storage Account from target cluster.
New file shares (volumes) could be created on it from target cluster. 
Problem is to access exising

**What you expected to happen**:
Volume is attached to pods on both clusters.

**How to reproduce it**:

StorageClass:

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-backup
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1000
- gid=1000
- mfsymlinks
- cache=none
- nobrl
- actimeo=30
parameters:
  location: eastus2
  resourceGroup: resource_group_with_storage_account
  secretNamespace: kube-system
  skuName: Standard_LRS
  storageAccount: storage_account_name
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

Simple app:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-test
  namespace: test
spec:
  storageClassName: azurefile-backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: test
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim-test
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

**Anything else we need to know?**:
This scenario could help in Disaster Recovery where sensitive data is kept on external Storage Account and recovered cluster could attach to file share.
If different storageClass settings are required or different provisioner like blob.csi.azure.com is required, please advice.
Please advice if disk.csi.azure.com provisioner can be used for this scenario.

**Environment**:
- CSI Driver version: azurefile-csi:v1.25.1
- Kubernetes version (use `kubectl version`): AKS 1.24.6
- OS (e.g. from /etc/os-release): Ubuntu 18
- Kernel (e.g. `uname -a`): as on AKS image
- Install tools: n/a
- Others: n/a
