### ISSUE TITLE
resourceGroup is not accepted for VolumeSnapshotClass

### ISSUE THREAD

**Issue by slawekww** [kubernetes-sigs/azurefile-csi-driver#1186]
**What happened**:
I want to keep snapshots for provisioner file.csi.azure.com in external Azure resource group.
Based on MS docs, it should be possible: https://learn.microsoft.com/en-us/azure/aks/azure-files-csi#storage-class-driver-dynamic-parameters

**What you expected to happen**:
Got error during VolumeSnapshot creation:

```
  Bound Volume Snapshot Content Name:  snapcontent-27dd8025-f534-4b85-84b1-867ebd9d5717
  Error:
    Message:     Failed to check and update snapshot content: failed to take snapshot of the volume aks_managed_resource_group#fdfe1dca601a94e3a953629#pvc-ce60a438-b50a-4f6a-90f3-4fd9783d6543###cascade-at: "rpc error: code = InvalidArgument desc = invalid parameter \"resourceGroup\" in storage class"
    Time:        2023-02-10T09:24:13Z
  Ready To Use:  false
```

**How to reproduce it**:

VolumeStorageClass:

```yaml
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Retain
driver: file.csi.azure.com
kind: VolumeSnapshotClass
metadata:
   labels:
    velero.io/csi-volumesnapshot-class: 'true'
  name: file.csi.azure.com
parameters:
  resourceGroup: external_resource_group
```

**Anything else we need to know?**:
Use velero 1.10 with EnableCSI driver on.
Goal is to store Snapshots on external resource group.

**Environment**:
- CSI Driver version: azurefile-csi v1.25.1
- Kubernetes version (use `kubectl version`): AKS 1.24.6
- OS (e.g. from /etc/os-release): Ubuntu 18 as part of AKS nodes
- Kernel (e.g. `uname -a`): n/a
- Install tools: velero 1.10 with EnableCSI driver
- Others: n/a
