### ISSUE TITLE
wrong restoresize in volumesnapshots

### ISSUE THREAD

**Issue by fragolinux** [kubernetes-sigs/azurefile-csi-driver#1187]
**What happened**:
i have an azurefile pvc with size=10gb, i take a volumesnapshot, it gets a restoresize 10x bigger, 100gb...

**What you expected to happen**:
pvc size and vs size should be the same, we're using azure cluster v1.21.7 and csidriver version is not managed by us, but included in cluster

**How to reproduce it**:

```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    csiDriver: v1.25.1
    snapshot: v5.0.1
  name: file.csi.azure.com
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-retain
mountOptions:
- mfsymlinks
- actimeo=30
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-core-data-lts
  namespace: lab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-retain
  volumeMode: Filesystem
---
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: file.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  name: lab-ha-storage-snapshots
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  labels:
    envName: lab
    frequency: ondemand
    instanceName: ha
  name: ha-storage-snapshots-ondemand-test
  namespace: lab
spec:
  source:
    persistentVolumeClaimName: ha-core-data-lts
  volumeSnapshotClassName: lab-ha-storage-snapshots

```

**Anything else we need to know?**:

**Environment**:
*Run following command to get CSI driver version:
```
kubectl get po -n kube-system -o yaml | grep mcr | grep azurefile

      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.25.1
      imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:0635db48614a5978a99201b5cdd1cfb612fa220e47d8e7ab93f8a4d4c3d0f978
```

- CSI Driver version: 1.25.1

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"3c28d5b50e68d9c6da51840bbdebf6bd0673dde5", GitTreeState:"clean", BuildDate:"2022-06-04T17:59:02Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

```

![image](https://user-images.githubusercontent.com/21192010/218067793-f5376fd0-1ef6-41a9-8684-94d5f8aef374.png)

![image](https://user-images.githubusercontent.com/21192010/218067827-e23704b9-2c86-4450-8d8c-c6b7134d4007.png)
