### ISSUE TITLE
Confusing documentation of accountAccessTier parameter

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/azurefile-csi-driver#1190]
In https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1109, a new StorageClass parameter `accountAccessTier` was added, however, its documentation leads to [access tiers for blob data](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview).

What does AzureFile have with blob data? How will setting various `accountAccessTier` values affect AzureFile billing / volume speed? How various combinations of `shareAccessTier` and `accountAccessTier` work together?

**Comment by andyzhangx** [comment]
@jsafrane yes, you are right, `accountAccessTier` is only for blob data. There are cases that one storage account could serve both blob and azure file share, but we should definitely add comments in driver parameters page.

**Comment by jsafrane** [comment]
So it just selects which StorageAccount will be used / created, so blob and file can share the same one? That's... unexpected :-).

**Comment by andyzhangx** [comment]
@jsafrane what about remove this parameter in the doc since it's mainly for blob storage? another option is set it as deprecated in the doc.

**Comment by jsafrane** [comment]
Both works for me.

Another related parameter I found confusing is `shareAccessTier`.

This SC does not work:

```
kind: StorageClass
metadata:
  name: azurefile-csi-test
parameters:
  shareAccessTier: Premium
```
Provisioning fails with `failed to create file share(pvc-5e6ee234-25ac-480b-9fca-4c19ecdbe05e) on account() type() subsID() rg(jsafrane-1-76gtw-rg) location() size(1), error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:759ecb2b-b01a-000c-5cd9-428159000000\nTime:2023-02-17T14:08:31.8000680Z`.

This one works:
```
kind: StorageClass
metadata:
  name: azurefile-csi-test
parameters:
  shareAccessTier: Premium
  skuName: Premium_LRS
```
So... why there is `shareAccessTier` when I must selected Premium_LRS in `skuName` already?
