### ISSUE TITLE
volumes with same ID created for different inline pod mounts

### ISSUE THREAD

**Issue by raafatseif** [kubernetes-sigs/azurefile-csi-driver#1206]
**What happened**:

Second deployment pod stuck at creation due to FailedMount error: `An operation with the given Volume ID csi-e0461bb83dcff31517e3591dd0f26a879599017206f99edc7885dabf8a3f2f9a already exists`.

**What you expected to happen**:

Create volume with unique VolumeID using volume generation [approach.](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/596-csi-inline-volumes/README.md#volumehandle-generation)

**How to reproduce it**:

Create a deployment using inline volume then create another similar deployment.

**Anything else we need to know?**:

Deployment manifest example:
```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: example-deployment
spec:
  selector:
    matchLabels:
      app: example
  replicas: 1
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: example
        command:
        - sleep
        - "infinity"
        volumeMounts:
        - mountPath: "/mnt/smb"
          name: example-volume-mount
      volumes:
      - name: example-volume-mount
        csi:
          driver: file.csi.azure.com
          volumeAttributes:
            server: smb-server
            shareName: share
            secretName: mysecret
            mountOptions: "actimeo=30,cache=strict,dir_mode=0775,file_mode=0775,gid=1000,nosharesock,uid=1000,vers=3.0,mfsymlinks"
```

**Environment**:

- CSI Driver version: v1.26.1
- Kubernetes version (use `kubectl version`): v1.22.8
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1049
- Install tools: ArgoCD

**Comment by andyzhangx** [comment]
@raafatseif I have tried your modified example, it works well. I think the issue is that you have specified `server: smb-server`, the correct format is `accountname.file.core.windows.net`, and you don't need to specify this parameter if you are not using private end point. And since the inline volume is the same, it should use same ID, that's expected, your issue is that the first volume mount does not succeed.

```
volumeAttributes:
            server: smb-server
            shareName: share
            secretName: mysecret
```
