### ISSUE TITLE
Static provisioning subscriptionID parameter is undocumented

### ISSUE THREAD

**Issue by DuncanCasteleyn** [kubernetes-sigs/azurefile-csi-driver#1208]
**Is your feature request related to a problem?/Why is this needed**

[Static provisioning](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#static-provisionbring-your-own-file-share) does take a subscriptionID parameter, but this is currently not documented.

**Describe the solution you'd like in detail**

That the parameter becomes documented

**Describe alternatives you've considered**

None

**Additional context**

**Comment by andyzhangx** [comment]
@DuncanCasteleyn I think it's actually supported in static provisioning, could you try add `subscriptionID: xxx` in the pv config, let me know whether it works.

**Comment by DuncanCasteleyn** [comment]
> @DuncanCasteleyn I think it's actually supported in static provisioning, could you try add `subscriptionID: xxx` in the pv config, let me know whether it works.

I tried this before creating the issue the subscription id in the scope error stayed the same.

**Comment by andyzhangx** [comment]
@DuncanCasteleyn what's your azure file csi driver version?

**Comment by DuncanCasteleyn** [comment]
@andyzhangx where can I check this?

**Comment by andyzhangx** [comment]
*Run following command to get CSI driver version:
kubectl get po -n kube-system -o yaml | grep mcr | grep azurefile

**Comment by DuncanCasteleyn** [comment]
v1.24.0, but i cannot share these logs because I work in the banking sector, I can however confirm from the logs that the subscription id of my cluster is still being used.

**Comment by andyzhangx** [comment]
> v1.24.0, but i cannot share these logs because I work in the banking sector, I can however confirm from the logs that the subscription id of my cluster is still being used.

@DuncanCasteleyn what's your azure file pv config?

**Comment by DuncanCasteleyn** [comment]
@andyzhangx 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: tnsnames
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: true
    volumeHandle: tnsnames  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      subscriptionID: {{ .Values.oracleDb.tnsnames.subscriptionId }}
      resourceGroup: {{ .Values.oracleDb.tnsnames.resourceGroup }}
      storageAccount: {{ .Values.oracleDb.tnsnames.storageAccount }}
      shareName: {{ .Values.oracleDb.tnsnames.shareName }}
  mountOptions:
    - dir_mode=0444
    - file_mode=0444
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
```
