### ISSUE TITLE
do we really need resourceGroup on a static volume when SA is not under the same RG?

### ISSUE THREAD

**Issue by mracfa** [kubernetes-sigs/azurefile-csi-driver#1266]
I have a static volume that is an azureFile share (in a different subscription and different RG than the aks nodes), where I don't specify the resourceGroup in the volumeAttributes and I'm able to mount it.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: blabla-storage
    volumeAttributes:
      shareName: files
    nodeStageSecretRef:
      name: blabla-storage-secret
      namespace: blabla
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
```

Here is my PVC:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: blabla
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: test-pv
  resources:
    requests:
      storage: 1Gi
```

Here is my pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: blabla
spec:
  containers:
  - image: nginx 
    name: test-container
    volumeMounts:
    - mountPath: /files
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-pvc
```

So my question is: why do we need the resource group?
It says: _"# optional, only set this when storage account is not in the same resource group as agent node"_  - and this is my case.

 Example I used: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/pv-azurefile-csi.yaml#L30. ?
