### ISSUE TITLE
VolumeResizeFailed warning message when succesfully resizing the PVC

### ISSUE THREAD

**Issue by bpinheiro19** [kubernetes-sigs/azurefile-csi-driver#1470]
**What happened**:
AKS cluster with pods which have a dynamically provisioned fileshare mounted. Resizing the PVC to increase the storage capacity, will cause the pods to get the following warning:
_NodeExpandVolume.NodeExpandVolume failed for volume "pvc-25d4362a-ad88-42e9-a94c-062e927a1ea0" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/file.csi.azure.com to not support node expansion_

The resizing works well but the warning appears nonetheless.

**What you expected to happen**:
No warning message since the resizing worked correctly.

**How to reproduce it**:
Its possible to reproduce using the following steps:
- Create or use existing AKS cluster
- Deploy the pvc with the yaml below
- Deploy the pod with the yaml below
- Edit/Redeploy the pvc with increase storage (e.g. 110Gi) 
- The fileshare will be increased succesfully but the pod will start having that warning message.

**PVC YAML**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-premium
```

**POD YAML**
```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azurefile
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
      name: nginx-azurefile
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
      volumeMounts:
        - name: persistent-storage
          mountPath: "/mnt/azurefile"
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: pvc-azurefile
```

**kubectl exec nginx-azurefile -it -- df -h | grep file.core.windows.net**
//XXXXXXXXXXXX.file.core.windows.net/pvc-25d4362a-ad88-42e9-a94c-062e927a1ea0  **110G**   64K  110G   1% /mnt/azurefile

**Pod Events**
```
Events:
  Type     Reason              Age                From               Message
  ----     ------              ----               ----               -------
  Normal   Scheduled           2m5s               default-scheduler  Successfully assigned default/nginx-azurefile to aks-systempool-25313989-vmss00000j
  Normal   Pulled              2m4s               kubelet            Container image "mcr.microsoft.com/oss/nginx/nginx:1.19.5" already present on machine
  Normal   Created             2m4s               kubelet            Created container nginx-azurefile
  Normal   Started             2m4s               kubelet            Started container nginx-azurefile
  Warning  VolumeResizeFailed  25s (x7 over 57s)  kubelet            NodeExpandVolume.NodeExpandVolume failed for volume "pvc-25d4362a-ad88-42e9-a94c-062e927a1ea0" : Expander.NodeExpand found CSI plugin kubernetes.io/csi/file.csi.azure.com to not support node expansion
```

**PVC Events**
```
Events:
  Type     Reason                  Age        From                                                                                               Message
  ----     ------                  ----       ----                                                                                               -------
  Normal   ExternalProvisioning    <invalid>  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
  Normal   Provisioning            <invalid>  file.csi.azure.com_csi-azurefile-controller-58c749b4c6-nrhxr_60c5b89d-e070-4f06-b40f-04f9e1b069e5  External provisioner is provisioning volume for claim "default/pvc-azurefile"
  Normal   ProvisioningSucceeded   <invalid>  file.csi.azure.com_csi-azurefile-controller-58c749b4c6-nrhxr_60c5b89d-e070-4f06-b40f-04f9e1b069e5  Successfully provisioned volume pvc-25d4362a-ad88-42e9-a94c-062e927a1ea0
  Warning  ExternalExpanding       <invalid>  volume_expand                                                                                      Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                <invalid>  external-resizer file.csi.azure.com                                                                External resizer is resizing volume pvc-25d4362a-ad88-42e9-a94c-062e927a1ea0
  Normal   VolumeResizeSuccessful  <invalid>  external-resizer file.csi.azure.com                                                                Resize volume succeeded
```

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: azurefile-csi:v1.26.7
- Kubernetes version (use `kubectl version`): 1.26.3
- OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): 5.15.0-1042-azure
- Install tools:
- Others:
