### ISSUE TITLE
Standard_ZRS will silently create a LRS share instead with NFS protocol

### ISSUE THREAD

**Issue by davidkarlsen** [kubernetes-sigs/azurefile-csi-driver#1480]
**What happened**:

Requesting a Standard_ZRS sku share will silently create a Premium_LRS instead

**What you expected to happen**:
Fail if not supported, create a Standard_ZRS if supported.

**How to reproduce it**:
See yamls below.
Go into portal, observe:

```shell
Performance
:
Premium
Replication
:
Locally-redundant storage (LRS)
Account kind
:
FileStorage
Provisioning state
:
Succeeded
Created
:
09/08/2023, 12:19:25
```

**Anything else we need to know?**:

**Environment**:
sc:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-standard-zrs-nfs
provisioner: file.csi.azure.com
parameters:
  # skuName: Premium_ZRS - The sku Sku: Premium_ZRS, Kind: FileStorage is not available in zone.
  skuName: Standard_ZRS
  protocol: nfs
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nconnect=4
```

pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disktest
  namespace: disktest
spec:
  storageClassName: azurefile-csi-standard-zrs-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

- CSI Driver version: v1.21.0
- Kubernetes version (use `kubectl version`): 1.25.12
- OS (e.g. from /etc/os-release): RHCOS
- Kernel (e.g. `uname -a`): 4.18.0-372.73.1.el8_6.x86_64
- Install tools:
- Others:
