### ISSUE TITLE
Issues with statically provisioned Azure NFS File Shares

### ISSUE THREAD

**Issue by tiny-hamster** [kubernetes-sigs/azurefile-csi-driver#1620]
**What happened**:
In our current setup, we assign a single Azure File Share to each AKS cluster, accessible via NFS. The cluster is mainly used for development and QA purposes, which involves running multiple copies of the same tasks in different namespaces. These namespaces are frequently deleted and recreated throughout the day.
Many of these tasks need persistent storage, and our aim is to create a unique folder for each namespace on the file share. Inside each of these folders, we want to create subfolders for each pod that requires persistent storage. We hope that this folder structure can be dynamically created by the driver, as we do not have control over the names of the namespaces, which can be random.
From Kubernetes' perspective, since Persistent Volumes (PV) are resources shared across the entire cluster and Persistent Volume Claims (PVC) have a one-to-one relationship with PV, we need to create a PV for each pod:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: release-1
    meta.helm.sh/release-namespace: random-ns-name-1
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app.kubernetes.io/instance: service-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pv-service-1-random-ns-name-1
    helm.sh/chart: service-1-1.0.0
    used-by-namespace: random-ns-name-1
  name: pv-service-1-random-ns-name-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: nfs.csi.k8s.io
    volumeAttributes:
      server: <storage-account>.file.core.windows.net
      share: /<storage-account>/<share-name>
    volumeHandle: <resource-group>#<storage-account>#<share-name>#service-1#random-ns-name-1
  mountOptions:
  - nconnect=8
  - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```
The initial question we have is whether `spec.csi.volumeHandler` is supposed to be unique in this particular situation, given that all PVs utilize the same underlying file share. Currently, we are maintaining its uniqueness by adding the service name and namespace name.

This is what a PVC looks like. We link it to a particular PV by setting a parameter called `spec.VolumeName`.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: release-1
    meta.helm.sh/release-namespace: random-ns-name-1
    pv.kubernetes.io/bind-completed: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: service-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-1
    helm.sh/chart: service-1-1.0.0
  name: service-1
  namespace: random-ns-name-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-service-1-random-ns-name-1
```
And here is an example of pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: service-1
  namespace: random-ns-name-1
spec:
  containers:
    - image: <docker-image>
      imagePullPolicy: IfNotPresent
      name: service-1
      volumeMounts:
        - mountPath: /opt
          name: data
          subPath: random-ns-name-1/service-1
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: service-1
```

In order to maintain at least a minimum level of storage separation, we only mount certain subfolders to the container using the `spec.containers[].volumeMounts[].subPath` parameter. The folder structure specified in this parameter typically doesn't exist beforehand, but is automatically created for us by kubelet.

This method generally works well, but there are some significant issues to consider:
1. When we delete a namespace with PV, the folder structure used for that namespace, such as `random-ns-name-1/*`, is not deleted regardless of the reclaim policy chosen. This probably happens because the PVC is not aware of any subfolder and it simply points to the root (`/`) of the file share. However, this is problematic for us because folders rapidly accumulate on the file share. Although it is possible to clean up outside of Kubernetes, this seems more like a temporary solution.
2. Occasionally, some pods refuse to run and get stuck in the ContainerCreating state due to failure in mounting a volume. Typically, the error message indicates this issue:
```
MountVolume.MountDevice failed for volume "pv-service-1-random-ns-name-1" : rpc error: code = Aborted desc = An operation with the given Volume ID <resource-group>#<storage-account>#<share-name>#service-1#random-ns-name-1 already exists 
```
The cause of this error is not very clear as we consistently append the service name and namespace to the PV name and volumeHandle, and we only run one replica of all services. The issue occurs sporadically on random nodes, and in certain cases, restarting the kubelet service appears to resolve the problem. However, this is not a valid long-term solution.

**What you expected to happen**:
1. For every namespace, folders created on a file share will be deleted along with the namespace itself.
2. There are no errors stating `An operation with the given Volume ID ... already exists`.

**How to reproduce it**:
Execute the manifests that have been provided above. We do not possess a specific method to replicate the Volume ID error. In our experience, this error usually arises when we deploy and tear down around 40 to 50 environments in the span of an hour. Each of these environments includes 5 to 10 pods that are configured to mount the same file share over NFS.

**Anything else we need to know?**:
N/A

**Environment**:

- CSI Driver version: `1.28.6`
- Kubernetes version (use `kubectl version`): `1.27.7` (AKS)
- OS (e.g. from /etc/os-release): `AKSUbuntu-2204gen2containerd-202311.07.0` (Azure-managed nodes)
- Kernel (e.g. `uname -a`):  `Linux aks-insecure2-15738093-vmss00002B 5.15.0-1051-azure #59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: `azcaf`

**Comment by andyzhangx** [comment]
@tiny-hamster I have no idea to how to solve this issue with static provisioning, while if you could put data into different file share, you could use this feature: 
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md#sharename-parameter-supports-following-pvpvc-metadata-conversion

with `shareName: prefix-${pvc.metadata.namespace}-${pvc.metadata.name}`, you could write data into different file shares, and that could ensure volumeHandle uniqueness in the pv created by k8s:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS     # available values: Premium_LRS, Premium_ZRS
  shareName: prefix-${pvc.metadata.namespace}-${pvc.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nconnect=4
  - noresvport
  - actimeo=30
```
