### ISSUE TITLE
matchTags does not generate new storageAccount

### ISSUE THREAD

**Issue by pniederlag** [kubernetes-sigs/azurefile-csi-driver#1713]
**What happened**:

provisioned dynamic kubernetes volume using custom-storage-class was created in existing storage-account

**What you expected to happen**:

we wanted to create a separate storage account

**How to reproduce it**:

pass parameters tags app=foo and matchTages to the storage-class, created pvc and pv using this storage-class. Notice that existing storage-account is reused and tags are neither appplied nor used to filter the usable storageaccount

```
parameters:
  matchTags: 'true'
  protocol: smb
  shareName: share-dummy
  skuName: Standard_LRS
  tags: app=foo
```

**Environment**:

- CSI Driver version: azurefile-csi:v1.28.7
- Kubernetes version (use `kubectl version`): Client Version: v1.28.2 Server Version: v1.27.7
