### ISSUE TITLE
PVC cloning does not work with private endpoints enabled on StorageClass

### ISSUE THREAD

**Issue by avanschie** [kubernetes-sigs/azurefile-csi-driver#1715]
**What happened**:
Creating a new PVC using the clone feature (i.e., declaring `spec.dataSource` referencing another existing PVC) does not work in the case where the StorageClass has the `networkEndpointType: privateEndpoint` parameter configured. The PVC remains in a `Pending` state. A `kubectl describe` on the PVC shows the following entry under the events:
```
Warning  ProvisioningFailed    3s (x3 over 17s)  file.csi.azure.com_csi-azurefile-controller-589df8676-cjz6k_7cc5300d-6005-4fc0-ac19-5d53fb9c42d2  failed to provision volume with StorageClass "clone-test": rpc error: code = Unknown desc = exit status 1
```

What works:
- Creating a new PVC without the clone feature works when `networkEndpointType` is set to `privateEndpoint`.
- The above scenario works when `networkEndpointType` is not set to `privateEndpoint`.

**What you expected to happen**:
I expect the cloned PVC to be created successfully when `networkEndpointType: privateEndpoint` is configured on the StorageClass.

**How to reproduce it**:
1. Create a StorageClass with the `networkEndpointType: privateEndpoint` parameter set.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: clone-test
parameters:
  skuname: Standard_ZRS
  networkEndpointType: privateEndpoint
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
```
2. Create a PVC using the StorageClass.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-one
  namespace: clone-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128M
  storageClassName: clone-test
```
3. Create another PVC using the clone feature (`spec.dataSource`), referencing the PVC created above. This PVC remains in a `Pending` state, with a `ProvisioningFailed` warning under the events. 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-two
  namespace: clone-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128M
  storageClassName: clone-test
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-one
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.29.2
- Kubernetes version (use `kubectl version`): 1.28.3
- OS (e.g. from /etc/os-release): Ubuntu 22.04 in AKS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
