### ISSUE TITLE
Add update strategy in helm chart

### ISSUE THREAD

**Issue by tropnikovvl** [kubernetes-sigs/azurefile-csi-driver#1880]
**Is your feature request related to a problem?/Why is this needed**
Hello!

I use this provider on only one node and during the update I get errors that the nodeport is occupied by the previous pod.
The ability to set a deployment strategy would help me solve this problem.

```yaml
spec:
  strategy:
    type: Recreate
```

Thank you in advance
