### ISSUE TITLE
Support for label selectors

### ISSUE THREAD

**Issue by aelmanaa** [kubernetes-sigs/azurefile-csi-driver#242]
Hello

do you support label selectors? I've just tried the following without success

pv

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels: 
    type: fast
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  csi:
    driver: file.csi.azure.com
    volumeAttributes:
      resourceGroup: rg
      shareName: name
      skuName: Standard_LRS
      storageAccount: sa
    volumeHandle: xxx#xxx#xxx#
  persistentVolumeReclaimPolicy: Retain

```

pvc

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: ""
  selector: 
    matchLabels: 
      type: fast
```

I get the following errors when checking the events

`no persistent volumes available for this claim and no storage class is set`

**Comment by andyzhangx** [comment]
try this example: https://docs.openshift.com/container-platform/3.3/install_config/storage_examples/binding_pv_by_label.html#binding-pv-by-label-pv-with-labels

label selector should  be supported by k8s itself

**Comment by aelmanaa** [comment]
what do you mean by "label selector should be supported by k8s itself" ?
it seems to be part of k8s specifications: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector

you suggest to change the driver? I'm opening an issue here because I prefer to use file.csi.azure.com (as It is completely integrated with Azure)

**Comment by andyzhangx** [comment]
the above config works in my k8s 1.14.8 cluster:
```
# k get pvc pvc1 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2020-04-21T14:38:30Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc1
  namespace: default
  resourceVersion: "2925994"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/pvc1
  uid: c553e0db-83dd-11ea-a0db-8e7fc28d9e05
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      type: fast
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv1
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  phase: Bound

```

**Comment by aelmanaa** [comment]
it works because you specify the volumeName. As per my understanding, the label selectors are useful in case the administrator deploy several PVs with different labels. 
Developers will then create a PVC and mention only the label.  A control loop will then find a matching PV and bind them together (as explained here: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding)

I suppose it's something like this:

- Check first if volume names match --> if yes then bind them
- If the volume name is not specified on the PVC then check if there a PV with enough storage resources
- If PVC mentions  selector --> the control loop will look for PVs with the right labels

I you check the example that you sent me (https://docs.openshift.com/container-platform/3.3/install_config/storage_examples/binding_pv_by_label.html#binding-pv-by-label-pv-with-labels) , the volumeName is not specified. Only the label selectors

**Comment by andyzhangx** [comment]
I used your example, it works:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels: 
    type: fast
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  csi:
    driver: file.csi.azure.com
    volumeAttributes:
      resourceGroup: rg
      shareName: name
      skuName: Standard_LRS
      storageAccount: sa
    volumeHandle: xxx#xxx#xxx#
  persistentVolumeReclaimPolicy: Retain
```
