### ISSUE TITLE
Azurefile with privateEndpoint forcibly disables NSGs from subnets network policy setting

### ISSUE THREAD

**Issue by lennartmoritz** [kubernetes-sigs/azurefile-csi-driver#2634]
**What happened**:
I created an Azurefile storageclass with `networkEndpointType: privateEndpoint` in my aks cluster that is already part of my virtual networks subnet. This subnet is already configured with:

`Private endpoint network policy: Route tables, Network security groups`

When I create a pvc for the Azurefile, the CSI driver will overwrite my setting to:
`Private endpoint network policy: Disabled`

This is an issue because actually i have an azure policy in place that denies changing the setting to disabled. So just for this test i had to create an exemption. When i change it back manually after creating the pvc then everything still works fine because my NSG is already set up to allow my azurefile to operate. Is this a behavior that can be changed in the driver?

**What you expected to happen**:
I expected my setting to remain as i had pre-configured it with.

**How to reproduce it**:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-azurefile-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  networkEndpointType: privateEndpoint
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - mfsymlinks
  - nosharesock
  - actimeo=30

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aks-file-claim
  namespace: storage
spec:
  storageClassName: my-azurefile-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 1.31.5
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
