### ISSUE TITLE
Restored snapshot is empty

### ISSUE THREAD

**Issue by michael-niemand** [kubernetes-sigs/azurefile-csi-driver#350]
Using the master version of the driver, I was able to create a snapshot, however the snapshot appears to be empty. 

Kubernetes version 1.17.7 AKS
kubectl version 1.18
using master branch version of the azurefile-csi-driver

Steps to reproduce:

1. Have pod with bound PVC, azure csi file driver, most recent version installed using [install script] this morning (new snapshotter!) (https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-master.md); write a file into mounted volume:
```
apiVersion: v1
  kind: Namespace
  metadata:
    name: sandbox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: test-pvc-1
  namespace: sandbox
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-csi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: write-data
  namespace: sandbox 
spec:
  template:
    spec:
      volumes:
      - name: volume 
        persistentVolumeClaim: 
          claimName: test-pvc-1
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', ' head -c 1073741824 </dev/urandom > /random/random.file && sleep 3600']
        volumeMounts: 
        - mountPath: /random
          name: volume
      restartPolicy: OnFailure
```
2. create a VolumeSnapshot of the PVC bound in 1, after state reaches ready to use=true.
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: file-volume-snapshot
  namespace: sandbox
spec:
  volumeSnapshotClassName: azure-file-snapclass
  source:
    persistentVolumeClaimName: test-pvc-1 
```
3. restore snapshot into new PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc-1
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
  namespace: sandbox
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    name: file-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io/v1beta1
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-csi
```
4. Read from restored PVC: 
```
apiVersion: batch/v1
kind: Job
metadata:
  name: check-restore
  namespace: sandbox
spec:
  template:
    spec:
      volumes:
      - name: volume 
        persistentVolumeClaim: 
          claimName: restore-pvc-1
      containers:
      - name: read 
        image: busybox
        command: ['sh', '-c', 'ls -hasl /random && sleep 3600']
        volumeMounts: 
        - mountPath: /random
          name: volume
      restartPolicy: OnFailure
```

--> the restored volume is empty.

I get an error in during snapshot creation, but I thought it was benign:  
`Warning  SnapshotFinalizerError  7m17s  snapshot-controller  Failed to check and update snapshot: snapshot controller failed to update file-volume-snapshot on API server: Operation cannot be fulfilled on volumesnapshots.snapshot.storage.k8s.io "file-volume-snapshot": the object has been modified; please apply your changes to the latest version and try again`
