### ISSUE TITLE
Support AzureBackup for Fileshares on pvc creation

### ISSUE THREAD

**Issue by schmichri** [kubernetes-sigs/azurefile-csi-driver#408]
**Is your feature request related to a problem?/Why is this needed**
Using the azurefiles-csi driver brings the circumstance that a backup of fresh created fileshares (wrapped in pvc creation) has to be created manually in azure. For "K8S as a Service" or failsafe deployment a workaround is need to e.g. always check for new fileshares, which is pretty unclean. 

**Describe the solution you'd like in detail**
A create solution would be if the azurefiles-csi driver create Azure Backups of Fileshares on creation or labeling of a PV and/or the PVC.  e.g. a VolumeClaimtemplate

```
volumeClaimTemplates:
- metadata:
    name: storage
    annotations:
      volume.beta.kubernetes.io/storage-class: azurefile-csi-retain
    labels:
      recovery-service-vault: my-central-rsv
      backup-policy: DefaultPolicy
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi
```

or via PVC

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcfiles2
  labels:
    recovery-service-vault: my-central-rsv
    backup-policy: DefaultPolicy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi
```

**Describe alternatives you've considered**
An alternative would be dedicated Storageclasses for backuped fileshares e.g. 

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-dailybackup
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Standard_ZRS  # available values: Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Premium_LRS
  storageAccount: myk8sstorageaccount
  recovery-service-vault: my-central-rsv
  backup-policy: DefaultPolicy
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Additional context**
