### ISSUE TITLE
azure files with nfs preview receiving "mount.nfs: access denied by server "

### ISSUE THREAD

**Issue by denniszielke** [kubernetes-sigs/azurefile-csi-driver#457]
**What happened**:
created an nfs storage account according to the docs but when trying to mount the pvc into a pod the pod gets stuck in creating with the following event output

```
<unknown>   Normal    Scheduled                pod/dbench-bjzrq   Successfully assigned default/dbench-bjzrq to aks-stoage-11118662-vmss000002
12s         Normal    SuccessfulAttachVolume   pod/dbench-bjzrq   AttachVolume.Attach succeeded for volume "pvc-0cf39873-5df7-451f-b8ed-3911f00f7753"
0s          Warning   FailedMount              pod/dbench-bjzrq   MountVolume.MountDevice failed for volume "pvc-0cf39873-5df7-451f-b8ed-3911f00f7753" : rpc error: code = Internal desc = volume(kub_ter_a_m_csisecurity_csisecurity_nodes_eastus#dzpremium1#pvcn-0cf39873-5df7-451f-b8ed-3911f00f7753#) mount "dzpremium1.file.core.windows.net:/dzpremium1/pvcn-0cf39873-5df7-451f-b8ed-3911f00f7753" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0cf39873-5df7-451f-b8ed-3911f00f7753/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs -o vers=4,minorversion=1,sec=sys dzpremium1.file.core.windows.net:/dzpremium1/pvcn-0cf39873-5df7-451f-b8ed-3911f00f7753 /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0cf39873-5df7-451f-b8ed-3911f00f7753/globalmount
Output: mount.nfs: access denied by server while mounting dzpremium1.file.core.windows.net:/dzpremium1/pvcn-0cf39873-5df7-451f-b8ed-3911f00f7753
19s         Normal    ExternalProvisioning     persistentvolumeclaim/dbench-pv-claim-nfs   waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
19s         Normal    Provisioning             persistentvolumeclaim/dbench-pv-claim-nfs   External provisioner is provisioning volume for claim "default/dbench-pv-claim-nfs"
18s         Normal    ProvisioningSucceeded    persistentvolumeclaim/dbench-pv-claim-nfs   Successfully provisioned volume pvc-0cf39873-5df7-451f-b8ed-3911f00f7753
12s         Normal    SuccessfulCreate         job/dbench                                  Created pod: dbench-bjzrq
```
**What you expected to happen**:
I would have expected the pod to run.

**How to reproduce it**:
Put the storage account in the MC_resource group, ensured permissions on controller identity in the MC_resource group and also tried with explicit secret instead of azure rbac permissions.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: kub_ter_a_m_csisecurity_csisecurity_nodes_eastus 
  storageAccount: dzpremium1
  protocol: nfs
  fsType: nfs
  #csi.storage.k8s.io/provisioner-secret-name: azure-secret
  #csi.storage.k8s.io/provisioner-secret-namespace: default
  #csi.storage.k8s.io/node-stage-secret-name: azure-secret
  #csi.storage.k8s.io/node-stage-secret-namespace: default
  #csi.storage.k8s.io/controller-expand-secret-name: azure-secret
  #csi.storage.k8s.io/controller-expand-secret-namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim-nfs
spec:
  storageClassName: azurefile-csi-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

**Anything else we need to know?**:
AKS Cluster is using managed identity, Kubernetes version 1.18.8 and using the EnableAzureDiskFileCSIDriver=true preview

**Environment**:
- CSI Driver version: 0.9
- Kubernetes version (use `kubectl version`): 1.18.8
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1026-azure
- Install tools:
- Others:
