### ISSUE TITLE
support mount specific folder inside that file share

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#480]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

if add the file share folder to the spec.csi.volumeHandle so it becomes volumeHandle: rgname#storageaccountname#filesharename#somefolder I am getting an error like that in the pod:
```
AttachVolume.Attach failed for volume "pv-user-scripts-bohdana-nfs" : rpc error: code = InvalidArgument desc = unsupported AccessMode(mode:MULTI_NODE_MULTI_WRITER ) for volume(rgname#storageaccountname#filesharename#somefolder)
```

subPath works indeed, but having that configured in PV is more convenient.
in-tree plugin for azurefile provides that if you specify shareName: `share/subfolder` as well

**Describe alternatives you've considered**

**Additional context**

**Comment by Jiawei0227** [comment]
@msau42 This might be the thing we talked about offline. 

@andyzhangx , we are facing this issue https://github.com/kubernetes/kubernetes/issues/97031 when doing subpath tests on Azurefile. And this feature might raise this issue to not only subpath volume but general volume, i.e. if user mount a specific folder and somehow the folder get deleted in the Azure console. Would this be a problem is some thing we should explore.

**Comment by andyzhangx** [comment]
actually this is already supported in both PV/PVC and inline volume configs in latest version:
 - PV config
 ```yaml
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      shareName: sharename/dirname
    nodeStageSecretRef:
      name: secret
      namespace: default
```
 - inline volume config
 ```yaml
  volumes:
    - name: persistent-storage
      csi:
        driver: file.csi.azure.com
        volumeAttributes:
          shareName: sharename/dirname
          secretName: secret
```

**Comment by vot4anto** [comment]
It is possible to use also a existing NFS file share with csi?  And which value are valid for volumeHandle parameters?
The id of nfs share for example?

**Comment by andyzhangx** [comment]
@vot4anto you have not installed azure file csi driver correctly, follow guide to provide logs: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed

And are you using taints to prevent azure file driver running on that node?

**Comment by vot4anto** [comment]
I don't install azure file csi driver because it is already installed with v.1.22.4

```
./kubectl --kubeconfig kubeconfig version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

And I check for the Storage Classes

```
./kubectl --kubeconfig kubeconfig get sc
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile               file.csi.azure.com   Delete          Immediate              true                   12m
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   12m
azurefile-csi-premium   file.csi.azure.com   Delete          Immediate              true                   12m
azurefile-premium       file.csi.azure.com   Delete          Immediate              true                   12m
default (default)       disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   12m
managed                 disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   12m
managed-csi             disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   12m
managed-csi-premium     disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   12m
managed-premium         disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   12m



$ ./kubectl --kubeconfig kubeconfig get po -o wide -n kube-system
NAME                                 READY   STATUS    RESTARTS   AGE   IP          NODE                             NOMINATED NODE   READINESS GATES
azure-ip-masq-agent-bc6mn            1/1     Running   0          12m   10.0.0.5    aks-system-12353726-vmss000000   <none>           <none>
cloud-node-manager-d6p5h             1/1     Running   0          12m   10.0.0.5    aks-system-12353726-vmss000000   <none>           <none>
coredns-845757d86-hvm6n              1/1     Running   0          15m   10.0.0.10   aks-system-12353726-vmss000000   <none>           <none>
coredns-845757d86-w7fg7              1/1     Running   0          11m   10.0.0.26   aks-system-12353726-vmss000000   <none>           <none>
coredns-autoscaler-7d56cd888-9kjkz   1/1     Running   0          15m   10.0.0.27   aks-system-12353726-vmss000000   <none>           <none>
csi-azuredisk-node-rcpq2             3/3     Running   0          12m   10.0.0.5    aks-system-12353726-vmss000000   <none>           <none>
csi-azurefile-node-rgx86             3/3     Running   0          12m   10.0.0.5    aks-system-12353726-vmss000000   <none>           <none>
kube-proxy-9mj2k                     1/1     Running   0          12m   10.0.0.5    aks-system-12353726-vmss000000   <none>           <none>
metrics-server-749c96b7cc-m2l7h      1/1     Running   0          15m   10.0.0.16   aks-system-12353726-vmss000000   <none>           <none>
tunnelfront-9dcc8c99d-2nqhd          1/1     Running   0          15m   10.0.0.39   aks-system-12353726-vmss000000   <none>           <none>

```

I can't see here the same resources in the link that you sent to me, maybe for a newer version ok aks?

BTW, I created the sc for nfs:
```
storageclass-azurefile-nfs.yaml 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
  skuName: Premium_LRS
  storageAccount: ******
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

./kubectl --kubeconfig kubeconfig get sc -o wide
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile               file.csi.azure.com   Delete          Immediate              true                   26m
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   26m
azurefile-csi-nfs       file.csi.azure.com   Retain          Immediate              true                   3s
azurefile-csi-premium   file.csi.azure.com   Delete          Immediate              true                   26m
azurefile-premium       file.csi.azure.com   Delete          Immediate              true                   26m
default (default)       disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   26m
managed                 disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   26m
managed-csi             disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   26m
managed-csi-premium     disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   26m
managed-premium         disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   26m

```

And after create only the PV since the share is already created

```

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    # take from terraform.tfstate "type": "azurerm_storage_share"
    volumeHandle: 
    volumeAttributes:
      resourceGroup: ******
      storageAccount: *******
      shareName: nfs
      protocol: nfs

./kubectl --kubeconfig kubeconfig get pv  -o wide
NAME           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE   VOLUMEMODE
pv-azurefile   1Ti        RWX            Retain           Available                                   13s   Filesystem

```
