### ISSUE TITLE
support arbitrary volume id in static pv

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#494]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently in static pv, if there is no secret provided, volume id format must be `rg#f5713de20cde511e8ba4900#pvc-file-dynamic-17e43f84-f474-11e8-acd0-000d3a00df41#`, actually it's not necessary, if user provides following parameters, volume id could be arbitrary string:
```
parameters:
  resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as agent node
  storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
  shareName: SHARE_NAME
```

**Describe alternatives you've considered**

**Additional context**
