### ISSUE TITLE
Azure file share is not deleted when the namespace is deleted

### ISSUE THREAD

**Issue by edwardsp** [kubernetes-sigs/azurefile-csi-driver#500]
**What happened**:

The SMB file share on Azure is not deleted when deleting a namespace.  This leaves resource on Azure even though the PVC is deleted.

**What you expected to happen**:

Any file shares should be deleted with the dynamic volumes when the dynamic volume is removed by deleting the namespace (as the PVC is deleted)

**How to reproduce it**:

**storageclass.yaml**
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-premazurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS
```

**pvc.yaml**
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: my-premazurefile
  resources:
    requests:
      storage: 100Gi
```

**pod.yaml**
```
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    resources:
      requests:
        cpu: 100m
        memory: 2048Mi
      limits:
        cpu: 250m
        memory: 2048Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
```

***Commands:***
```
kubectl create namespace mynamespace
kubectl -n mynamespace apply -f storageclass.yaml
kubectl -n mynamespace apply -f pvc.yaml
kubectl -n mynamespace apply -f pod.yaml
kubectl delete mynamespace
```

Now, you can check in the portal and see the SMB share is still there.

**Anything else we need to know?**:

The SMB file share is correctly cleaned up if the pvc is deleted directly (rather than indirectly through deleting the namespace)

**Environment**:
- CSI Driver version:
built in
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):
WSL2
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
