### ISSUE TITLE
failed to provision volume with StorageClass "azurefile-csi": volume content source missing

### ISSUE THREAD

**Issue by michaelcourcy** [kubernetes-sigs/azurefile-csi-driver#517]
**What happened**:

When restoring a pvc from a snapshot the snapshot stay in pending state 

```
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-clone
spec:
  storageClass: azurefile-csi
  dataSource:
    name: azurefile-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi
```

When checking the status of the pvc I read the message `failed to provision volume with StorageClass "azurefile-csi": volume content source missing` 
```
oc describe pvc pvc-azurefile-clone
Name:          pvc-azurefile-clone
Namespace:     default
StorageClass:  azurefile-csi
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      azurefile-volume-snapshot
Mounted By:  <none>
Events:
  Type     Reason                Age                From                                                                                       Message
  ----     ------                ----               ----                                                                                       -------
  Warning  ProvisioningFailed    23s                file.csi.azure.com_aks-nodepool1-36077706-vmss000000_b4ad05e3-f8f6-4a8c-aed2-f1c2ed2e65b1  failed to provision volume with StorageClass "azurefile-csi": volume content source missing
  Normal   Provisioning          22s (x2 over 24s)  file.csi.azure.com_aks-nodepool1-36077706-vmss000000_b4ad05e3-f8f6-4a8c-aed2-f1c2ed2e65b1  External provisioner is provisioning volume for claim "default/pvc-azurefile-clone"
  Normal   ExternalProvisioning  6s (x3 over 24s)   persistentvolume-controller                                                                waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
```

**What you expected to happen**:
the pvc should transition to bound state and content should be there 

**How to reproduce it**:

Install 
```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/install-driver.sh | bash -s master snapshot
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/snapshot/volumesnapshotclass-azurefile.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/pvc-azurefile-csi.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/snapshot/volumesnapshot-azurefile.yaml
```

Then try to restore with the pvc spec 
```
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-clone
spec:
  storageClass: azurefile-csi
  dataSource:
    name: azurefile-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): AKS 1.18
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
