### ISSUE TITLE
Mounting error (2) - No such file or directory

### ISSUE THREAD

**Issue by Insighter2k** [kubernetes-sigs/azurefile-csi-driver#603]
**What happened**:
I am trying to add a fileshare to my kubernetes environment via persistentVolume which ends in the following error

"mount error(2): No such file or directory Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)"
The file is existing and secret is passed correctly

**What you expected to happen**:
Attaching volume and mounting the fileshare to the mount path

**How to reproduce it**:

This is my current configuration

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-csi-smb-devakstestpreviewfs-test-share
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  # https://linux.die.net/man/8/mount.cifs
    - nosharesock
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: pv-csi-smb-devakstestpreviewfs-test-share-1 # make sure it's a unique id in the cluster
    volumeAttributes:
      resourceGroup: dev-aks  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: devakstestpreviewfs
      shareName: test-share-smb  # only file share name, don't use full path
    nodeStageSecretRef:
      name: smb-devakstestpreviewfs-test-share
      namespace: dev-csharp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-csi-smb-devakstestpreviewfs-test-share
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-csi-smb-devakstestpreviewfs-test-share
  storageClassName: ""
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dev-rest-api-local-with-azure-fileshare
  namespace: dev-csharp
  labels:
    env: dev
    os: lin
    target: azure-fileshare
    type: rest-api
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      os: lin
      target: azure-fileshare
      type: rest-api
  template:
    metadata:
      namespace: dev-csharp
      labels:
        env: dev
        os: lin
        target: azure-fileshare
        type: rest-api
    spec:
      containers:
        - name: dev-restclient-azure-fileshare-cr
          image: 'devakstestcr.azurecr.io/restclientlinux:ubuntu-2004-local-latest'
          ports:
            - containerPort: 443
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
          volumeMounts:
              - name: azure
                mountPath: /mnt/azure
      restartPolicy: Always
      nodeSelector:
        agentpool: lin1
      imagePullSecrets:
        - name: <crSecret>
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: 
            pvc-csi-smb-devakstestpreviewfs-test-share
```

**Anything else we need to know?**:
The docker image is using Ubuntu 20.04
5.0.4-focal-amd64 => https://hub.docker.com/_/microsoft-dotnet-aspnet
5.0.201-focal-amd64 => https://hub.docker.com/_/microsoft-dotnet-sdk

**Environment**:
- CSI Driver version: I really don't know. I just setup new AKS cluster with preview features as described here => https://docs.microsoft.com/de-de/azure/aks/csi-storage-drivers
- Kubernetes version (use `kubectl version`): latest preview 1.20.2
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
