### ISSUE TITLE
NFS rsize/wsize

### ISSUE THREAD

**Issue by MaxMelcher** [kubernetes-sigs/azurefile-csi-driver#619]
**Is your feature request related to a problem?/Why is this needed**
We want to transfer 50.000 small files (large php application) to nfs azure file storage. It takes 44min on a 100GB share. 

**Describe the solution you'd like in detail**
we want to provide the rsize/wsize when mounting the nfs share to get more throughput with small files.

**Describe alternatives you've considered**
Alternative would be to mount the share by ourselves or use Azure NetApp Files.

Would a driver parameter help?

**Comment by andyzhangx** [comment]
try below mount options, However a 100 GiB share is way too small, hitting throttling

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - rsize=1048576    # default value
  - wsize=1048576  # default value
```
