### ISSUE TITLE
mount failed: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/xxx/globalmount does not exist

### ISSUE THREAD

**Issue by josegob** [kubernetes-sigs/azurefile-csi-driver#620]
**What happened**:
After I have updated my AKS node pool to Kubernetes version 1.20.5, I'm not able to mount different NFS volumes at the same time in the same node.

**What you expected to happen**:
I should be able to create multiple pods with different NFS volumes at the same time similar to when my node pool was in Kubernetes version 1.19.7.

**How to reproduce it**:
Create a dummy pod with a NFS volume. Then create a second pod with a different NFS volume. This second pod will stuck in "ContainerCreating" phase.

**Anything else we need to know?**:
The logs I'm getting after "kubectl describe pod x" are the following:

````
E0420 12:44:33.609222       1 utils.go:123] GRPC error: rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/globalmount" at "/var/lib/kubelet/pods/2c1ed1ad-5623-44dd-9fea-928f1bb3de09/volumes/kubernetes.io~csi/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/globalmount /var/lib/kubelet/pods/2c1ed1ad-5623-44dd-9fea-928f1bb3de09/volumes/kubernetes.io~csi/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/mount
Output: mount: /var/lib/kubelet/pods/2c1ed1ad-5623-44dd-9fea-928f1bb3de09/volumes/kubernetes.io~csi/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/globalmount does not exist.
````

The logs I'm getting after "kubectl describe pvc x" are the following:
````
  Normal  WaitForFirstConsumer   5m24s  persistentvolume-controller                                                                  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning   5m24s  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
  Normal  Provisioning           5m24s  file.csi.azure.com_aks-akswepnp002-41589637-vmss000002_657b51a2-23a5-4802-a653-ce4145d449c0  External provisioner is provisioning volume for claim "default/dummy-pvc-nfs"
  Normal  ProvisioningSucceeded  5m24s  file.csi.azure.com_aks-akswepnp002-41589637-vmss000002_657b51a2-23a5-4802-a653-ce4145d449c0  Successfully provisioned volume pvc-fbc6febc-ff05-4818-a910-15312a260612
````

**Environment**:
- CSI Driver version: Master version
- Kubernetes version (use `kubectl version`): 
````
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
````
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
so this issue only exists in 1.20.5?

**Comment by josegob** [comment]
@andyzhangx I would say yes because yesterday my AKS node pools was on verison 1.19.7 and it was working properly.
Any idea of a existing workaround? I have tried to recreate a AKS nodepool with version 1.19.7 but I got this message from the Azure Portal "We are unable to serve this request due to an internal error"

**Comment by andyzhangx** [comment]
what's your storage class and pvc configs? does the NFS examples works in your cluster?
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/storageclass-azurefile-nfs.yaml
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/statefulset.yaml

**Comment by josegob** [comment]
My storage class configuracion is the following:

````
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: My-RG
  storageAccount: My-Storageaccount
  shareName: aksnfsshare002
  server: xxx.privatelink.file.core.windows.net
  protocol: nfs
allowVolumeExpansion: true  
reclaimPolicy: Retain
volumeBindingMode: Immediate
````

My PVC config examples:

````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-pvc-nfs
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 100Gi
````
````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-pod-2
  namespace: dummy-ns-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-nfs2
  resources:
    requests:
      storage: 1Gi
````

On the other hand, the mentioned examples work properly

**Comment by andyzhangx** [comment]
`/var/lib/kubelet/pods/2c1ed1ad-5623-44dd-9fea-928f1bb3de09/volumes/kubernetes.io~csi/pvc-26944d95-e1b6-4fc6-89b2-34d4c4ff63ce/mount` is invalid in your agent node, not sure why? It's better log on to the node, and then run `mount | grep nfs | uniq` to take a look.

**Comment by josegob** [comment]
Not sure if this the logs you are asking about:

````
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-217a0b8b-6986-45f3-8190-045c41492895/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002 on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volumes/kubernetes.io~csi/pvc-217a0b8b-6986-45f3-8190-045c41492895/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002/soc-intelligent/misp-first on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volume-subpaths/pvc-217a0b8b-6986-45f3-8190-045c41492895/nginx/1 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002/soc-intelligent/misp-first/timestamp on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volume-subpaths/pvc-217a0b8b-6986-45f3-8190-045c41492895/nginx/2 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
````

**Comment by josegob** [comment]
Not sure if this the logs you are asking about:

````
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-217a0b8b-6986-45f3-8190-045c41492895/globalmount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002 on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volumes/kubernetes.io~csi/pvc-217a0b8b-6986-45f3-8190-045c41492895/mount type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/PATH/TO/FILE on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volume-subpaths/pvc-217a0b8b-6986-45f3-8190-045c41492895/nginx/1 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
NFS_FILE_NAME.privatelink.file.core.windows.net:/NFS_FILE_NAME/aksnfsshare002/PATH/TO/FILE on /var/lib/kubelet/pods/97cd3493-2f5b-45c2-9822-133c6e5b26ae/volume-subpaths/pvc-217a0b8b-6986-45f3-8190-045c41492895/nginx/2 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=INTERNAL_IP,local_lock=none,addr=INTERNAL_IP)
````

**Comment by josegob** [comment]
I have been able to create a new AKS nodepool with vesion 1.19.7 as a workaround. Everything is working now as expected

**Comment by andyzhangx** [comment]
I hit the same transient issue on Azure File(SMB) mount, as I could observe, it only happens in k8s v1.20 in a little possibility, not sure what's wrong(rerun the test usually works):
```
May  2 15:06:55.766: INFO: At 2021-05-02 14:51:38 +0000 UTC - event for azurefile-volume-tester-2tpth: {kubelet k8s-agentpool1-32450920-vmss000000} FailedMount: MountVolume.SetUp failed for volume "azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7" : rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount" at "/var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount /var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount
Output: mount: /var/lib/kubelet/pods/ed800670-69de-4a1e-902c-e0ceeca4ec68/volumes/kubernetes.io~csi/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/azurefile-4885-file.csi.azure.com-preprovsioned-pv-ql6t7/globalmount does not exist.
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azurefile-csi-driver/642/pull-azurefile-csi-driver-e2e-vmss/1388861197100519424/build-log.txt

```
print out all nodes status ...
NAME                                 STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-agentpool1-32450920-vmss000000   Ready    agent    42m   v1.20.5   10.240.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1044-azure   docker://19.3.14
k8s-agentpool1-32450920-vmss000001   Ready    agent    42m   v1.20.5   10.240.0.5     <none>        Ubuntu 18.04.5 LTS   5.4.0-1044-azure   docker://19.3.14
k8s-master-32450920-0                Ready    master   42m   v1.20.5   10.240.255.5   <none>        Ubuntu 18.04.5 LTS   5.4.0-1044-azure   docker://19.3.14
```

it's similar to this issue: https://github.com/kubernetes/kubernetes/issues/78024#issuecomment-830983722

**Comment by andyzhangx** [comment]
I think it's related to https://github.com/kubernetes/kubernetes/pull/88759/files#r624850275, and only broken from k8s 1.20

**Comment by josegob** [comment]
Thanks for check it, @andyzhangx . What's your recommendation on this? Should I keep my nodepool in K8s v1.19.7 until there is an available fix?

**Comment by andyzhangx** [comment]
> Thanks for check it, @andyzhangx . What's your recommendation on this? Should I keep my nodepool in K8s v1.19.7 until there is an available fix?

Yes, I will keep tracking this issue.

**Comment by andyzhangx** [comment]
@josegob I found I could not repro this issue in my k8s 1.20.5 cluster, could you provide the exact detailed config including the pod configs? It's better as detailed as possible, I tried creating a few pods with different NFS volumes, has no luck to get the repro, thanks.

**Comment by josegob** [comment]
Hello @andyzhangx 
The storage class used to create the NFS is the following:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: MY-RG
  storageAccount: my-storage-account
  shareName: MY-NFS-SHARE-NAME
  server: my-storage-account.privatelink.file.core.windows.net
  protocol: nfs
allowVolumeExpansion: true  
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```
Volume pod configuration:
````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ...
  namespace: ...
  labels:
        app: ...
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ...
  template:
    metadata:
      name: ...
      labels:
        app: ...
    spec:
      containers:                        
        volumeMounts:        
        - mountPath: "/my-mount-path"
          name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: my-local-volume
````
PVC config:
````
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-volume
  namespace: ...
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 1Gi
````

Not sure if you need any extra configuration. If so, please let me know and I will try to provide you with it.
