### ISSUE TITLE
Output: mount error(2): No such file or directory

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes-sigs/azurefile-csi-driver#687]
**What happened**:
Error when Pod mounts a provisioned Volume

```
ks get events

LAST SEEN   TYPE      REASON        OBJECT                        MESSAGE

54s         Warning   FailedMount   pod/statefulset-azurefile-0   MountVolume.MountDevice failed for volume "pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e" : rpc error: code = Internal desc = volume(<ResourceGroup>#pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e#) mount "//<STORAGE-ACCOUNT>.file.core.windows.net/pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e/globalmount" failed with mount failed: exit status 32

Mounting command: mount

Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,cache=strict,nosharesock,actimeo=30,<masked> //<STORAGE-ACCOUNT>.file.core.windows.net/pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e/globalmount
Output: mount error(2): No such file or directory
```

The storage class looks like below
```yaml
k get sc/<NAME> -o yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: <name>
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
parameters:
  resourceGroup: <ResourceGroup>
  storageAccount:<STORAGE-ACCOUNT>
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The AKS’s MSI has a contributor access to the StorageAccount so its able to create Azure File Shares when we have a PVC using the above Storage Class, but when we create a pod that mounts the volume then the above error happens.

is the CSIDriver suppose to create the below path in AKS 1.20.2?
```
/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6a256ac3-8344-44ca-8f54-db3881f2e84e/globalmount
Output: mount error(2): No such file or directory
```

**What you expected to happen**:
Pod should be able to mount  the volume

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:  1.2.0
- Kubernetes version (use `kubectl version`): AKS 1.20.2
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`):
- Install tools: used  [this](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v1.2.0.md) method to install CSI driver
- Others:
