### ISSUE TITLE
Provision volume failed: invalid parameter "csi.storage.k8s.io/pvc/name" in storage class

### ISSUE THREAD

**Issue by josegob** [kubernetes-sigs/azurefile-csi-driver#692]
**What happened**:

A PVC with a Azure file storage class is not being provisioned therefore, the pod is stuck in pending state 

**What you expected to happen**:

The PVC should be provisioned without any issue and then the pod should change its state.

**How to reproduce it**:

Create a Storage Class as follow:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: RG_GROUP  # optional, required only when storage account is not in the same resource group as your agent nodes
  storageAccount: AZURE_STORAGE_ACCOUNT
  shareName: STORAGE_ACCOUNT_SHARE_NAME
  server: xxxx.privatelink.file.core.windows.net
  protocol: nfs
allowVolumeExpansion: true  
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

Then create a deploy:
```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dummy-nginx
spec:
  selector:
    matchLabels:
      app: dummy
  replicas: 1 
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure-nfs
            mountPath: /mnt/nfs               

      volumes:       
      - name: azure-nfs
        persistentVolumeClaim:
          claimName: dummy-pvc-nfs        

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dummy-pvc-nfs
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: azurefile-csi-nfs
  resources:
    requests:
      storage: 100Gi
```

If you describe the PVC you get the following:

```
Name:          dummy-pvc-nfs
Namespace:     default
StorageClass:  azurefile-csi-nfs
Status:        Bound
Volume:        pvc-29028647-94ef-4095-94e9-205922f4e65a
Labels:        <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  ROX
VolumeMode:    Filesystem
Used By:       dummy-nginx-77f889f855-7xtgl
Events:
  Type     Reason                 Age                   From                                                                                         Message
  ----     ------                 ----                  ----                                                                                         -------
  Normal   WaitForFirstConsumer   5m8s                  persistentvolume-controller                                                                  waiting for first consumer to be created before binding
  Warning  ProvisioningFailed     5m (x4 over 5m7s)     file.csi.azure.com_aks-akswepnp001-41589637-vmss000000_e34c49b8-8867-49ae-97bb-788ab8fef890  failed to provision volume with StorageClass "azurefile-csi-nfs": rpc error: code = Unknown desc = invalid parameter "csi.storage.k8s.io/pvc/name" in storage class
  Warning  ProvisioningFailed     4m52s                 file.csi.azure.com_aks-akswepnp001-41589637-vmss000000_e34c49b8-8867-49ae-97bb-788ab8fef890  failed to provision volume with StorageClass "azurefile-csi-nfs": rpc error: code = Unknown desc = invalid parameter "csi.storage.k8s.io/pv/name" in storage class
  Normal   Provisioning           4m36s (x6 over 5m7s)  file.csi.azure.com_aks-akswepnp001-41589637-vmss000000_e34c49b8-8867-49ae-97bb-788ab8fef890  External provisioner is provisioning volume for claim "dummy-pvc-nfs"
```

**Anything else we need to know?**:

As a workaround I downgroaded to driver version v1.3.0 and everything is working as usual.

**Environment**:
- CSI Driver version: Master version
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"54684493f8139456e5d2f963b23cb5003c4d8055", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:59Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
