### ISSUE TITLE
Ephemeral mounts not respecting dir_mode and file_mode

### ISSUE THREAD

**Issue by jabbera** [kubernetes-sigs/azurefile-csi-driver#733]
**What happened**: For Ephemeral mounts permissions are always 777 instead of what is specified in mount options:

**What you expected to happen**: dir_mode and file_mode to be respected.

**How to reproduce it**: Use inline demo but change mount options

```
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azurefile-inline-volume
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
      name: nginx-azurefile
      command:
        - "/bin/bash"
        - "-c"
        - set -euo pipefail; while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
      volumeMounts:
        - name: persistent-storage
          mountPath: "/mnt/azurefile"
  volumes:
    - name: persistent-storage
      csi:
        driver: file.csi.azure.com
        volumeAttributes:
          shareName: <SNIP>  # required
          resourceGroup: <SNIP>
          storageAccount: <SNIP>
          mountOptions: "dir_mode=0700,file_mode=0700,cache=strict,actimeo=30"  # optional
```

**Anything else we need to know?**:

As you can see in this log, the request is for 700 but the mount is for 777. As you can see there are extra mount options appended in the log and user specified are comma separated while the defaults being added by appendDefaultMountOptions are space separated:

actimeo=30 **dir_mode=0700,file_mode=0700**,uid=<SNIP>,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl **dir_mode=0777 file_mode=0777** mfsymlink

It appears that this is being called and not processed properly. mountOptions should be split on "," before being passed in.

func appendDefaultMountOptions(mountOptions []string) []string {

```
I0707 15:00:48.055909       1 nodeserver.go:224] cifsMountPath(/var/lib/kubelet/pods/241945b6-38ab-4654-9384-cf6b16eb4d5c/volumes/kubernetes.io~csi/user-home/mount) fstype() volumeID(csi-05e79a76dd118ae38d2632e76262af8ee9cbccefd65c232bd468e12981b80bda) context(map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:jupyter-mbarry csi.storage.k8s.io/pod.namespace:jhub csi.storage.k8s.io/pod.uid:241945b6-38ab-4654-9384-cf6b16eb4d5c csi.storage.k8s.io/serviceAccount.name:default getaccountkeyfromsecret:true mountOptions:dir_mode=0700,file_mode=0700,uid=1631642866,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl resourceGroup:<SNIP> secretnamespace:jhub shareName:user storageAccount:<SNIP> storageaccount:]) mountflags([]) mountOptions([actimeo=30 dir_mode=0700,file_mode=0700,uid=1631642866,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl dir_mode=0777 file_mode=0777 mfsymlinks])
I0707 15:00:48.056004       1 mount_linux.go:175] Mounting cmd (mount) with arguments (-t cifs -o actimeo=30,dir_mode=0700,file_mode=0700,uid=<SNIP>,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl,dir_mode=0777,file_mode=0777,mfsymlinks,<masked> //<SNIP>.file.core.windows.net/user /var/lib/kubelet/pods/241945b6-38ab-4654-9384-cf6b16eb4d5c/volumes/kubernetes.io~csi/user-home/mount)
```

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.20.5
- OS (e.g. from /etc/os-release): AKS
- Kernel (e.g. `uname -a`): AKS 
- Install tools:AKS
- Others:
