### ISSUE TITLE
Could not mount using dynamic volumes across namespaces

### ISSUE THREAD

**Issue by fraenkel** [kubernetes-sigs/azurefile-csi-driver#753]
**What happened**:
Deployed our setup that works fine on 1.20.7 but fails on 1.21.2.

```
E0803 00:37:11.338040       1 utils.go:123] GRPC error: rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/shared-nsB/globalmount" at "/var/lib/kubelet/pods/f54dc3b3-4534-4484-8adf-b38cdb32e161/volumes/kubernetes.io~csi/shared-nsB/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/shared-nsB/globalmount /var/lib/kubelet/pods/f54dc3b3-4534-4484-8adf-b38cdb32e161/volumes/kubernetes.io~csi/shared-nsB/mount
Output: mount: /var/lib/kubelet/pods/f54dc3b3-4534-4484-8adf-b38cdb32e161/volumes/kubernetes.io~csi/shared-nsB/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/shared-nsB/globalmount does not exist.
```

We have a storage class that looks like:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared
mountOptions:
- mfsymlinks
- noperm
parameters:
  secretNamespace: nsA
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Originally the provisioner was `kubernetes.io/azure-file` and there was no secretNamespace.
Without the secretNamespace, it csi-azurefile-node was failing trying to get the secrets, so it was added and we hit this problem.

**What you expected to happen**:
Some how make it work in 1.21+

**How to reproduce it**:
We create 2 PVCs in different namespaces (unfortunately). 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-store
  namespace: nsA
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: shared
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nsB
  namespace: nsB
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: shared
```

We create the PVC `shared-store` in nsA prior to `shared-nsB`. Both are bound, however I do notice that the reclaim policies are Delete and Retain respectively.

We create deployment in nsB which uses the PVC.
```
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: shared-nsB
```

**Anything else we need to know?**:

The cifs mounts on the failing node:
```
//f24e39abe3aed418dad5d08.file.core.windows.net/pvc-82fbbca3-e300-4bb2-84cd-58e3155402b9 on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-82fbbca3-e300-4bb2-84cd-58e3155402b9/globalmount type cifs (rw,relatime,vers=3.1.1,cache=strict,username=f24e39abe3aed418dad5d08,uid=0,noforceuid,gid=0,noforcegid,addr=20.60.20.40,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,mfsymlinks,noperm,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=30)
//f24e39abe3aed418dad5d08.file.core.windows.net/pvc-82fbbca3-e300-4bb2-84cd-58e3155402b9 on /var/lib/kubelet/pods/6c0b3a10-0e74-4b98-a2a5-620348c3031d/volumes/kubernetes.io~csi/pvc-82fbbca3-e300-4bb2-84cd-58e3155402b9/mount type cifs (rw,relatime,vers=3.1.1,cache=strict,username=f24e39abe3aed418dad5d08,uid=0,noforceuid,gid=0,noforcegid,addr=20.60.20.40,file_mode=0777,dir_mode=0777,soft,persistenthandles,nounix,serverino,mapposix,mfsymlinks,noperm,rsize=1048576,wsize=1048576,bsize=1048576,echo_interval=60,actimeo=30)
```

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.21.2
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1051-azure
- Install tools:
- Others:
