### ISSUE TITLE
Allow BYO Existing Storage Account across Subscriptions with Storage Class

### ISSUE THREAD

**Issue by raykao** [kubernetes-sigs/azurefile-csi-driver#786]
**Is your feature request related to a problem?/Why is this needed**

It would be a better experience if we can connect an existing Storage Account/File Share in another Subscription (same Tenant) via the Storage Class since it is potentially capable of acquiring the Storage Account Access Key on behalf of clusterAdmins/Users.  Currently this is not possible as you can't enter the subscriptionId of the secondary subscription/account via the parameters of the StorageClass.  It's preferable to let the CSI driver manage the Access Keys/Secrets vs. manually creating the secrets.

**Describe the solution you'd like in detail**

- Be able to set a subscriptionId Parameter for the storage account (See Yaml example below)
- Driver can then get Storage Account Access Key in subscription2
- Driver can then store Access Key as kubernetes secret as it currently does
- Driver can do create/delete etc. operations as it currently can against subscription2

Presumed YAML example:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-preprovis
provisioner: file.csi.azure.com
parameters:
  server: xxx.privatelink.file.core.windows.net
  shareName: xxxfileshare
  resourceGroup: xxxRG
  subscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: 
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

**Describe alternatives you've considered**

The docs currently have an option for using PV/PVC to mount a Storage Account/fileShare in a Secondary Subscription.  This works however it does require manual creation of k8s secret vs. "automatic" via Cluster/Node MSI as a PV does not have the ability to retrieve AccessKeys and save it to a k8s secret.

I've attempted to manually add a the secret (accountName + accessKey) and pass in secretName paramater and allow the Storage Class to do it's thing - however it still results in a mount error regarding bad credentials.

**Additional context**

I've Forked and started to resolve this however I'm reached the limit of my understanding how the CSI driver makes calls to Azure and the Storage Account to retrive and save Access Keys.

1. I've added the ability in ```pkg/azurefile/azure.go``` to accept the ```subscriptionId``` parameter [here](https://github.com/raykao/azurefile-csi-driver/blob/d63dbf220fd500e115bd660d4b180e29a52e2fd3/pkg/azurefile/azurefile.go#L120)
2. I've added the ability to default to the cloud-config subscriptionId if the new parameter is not supplied [here](https://github.com/raykao/azurefile-csi-driver/blob/d63dbf220fd500e115bd660d4b180e29a52e2fd3/pkg/azurefile/azurefile.go#L543)
3. I've updated references to the ```GetAccountInfo``` func accordingly for now
4. I believe I have added/updated a tests to reflect the above

**Comment by raykao** [comment]
Including @kendallroden for visibility/tracking

**Comment by andyzhangx** [comment]
thanks for raising this feature request, that would require add a `subscriptionId` into all storage related operations, it should be doable, will take a look later, thanks.

**Comment by andyzhangx** [comment]
use account name & key as a k8s secret should work, follow guide here:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account

you could define a storage class like following:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/provisioner-secret-name: azure-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azure-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: azure-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  server: accountname.privatelink.file.core.windows.net
  shareName: SHARE_NAME
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```
