### ISSUE TITLE
networkEndpointType: privateEndpoint with Azure private DNS zone in another subscription

### ISSUE THREAD

**Issue by damhau** [kubernetes-sigs/azurefile-csi-driver#829]
**What happened**:

I'm trying to use the networkEndpointType: privateEndpoint feature with a private dns zone that is in another subscription than the AKS nodes.

**What you expected to happen**:

The dns record for the private endpoint should be created in the private dns zone in the other subscription.

**How to reproduce it**:

Create a storage class:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  networkEndpointType: privateEndpoint
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: 
  - dir_mode=0775
  - file_mode=0775
  - uid=82
  - gid=82
  - mfsymlinks
  - cache=strict
  - actimeo=30
  - nosharesock

Create a PVC:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: test
  resources:
    requests:
      storage: 100Gi

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.7
- Kubernetes version (use `kubectl version`): 1.21
- OS (e.g. from /etc/os-release): Azure AKS Node
- Kernel (e.g. `uname -a`): ?
- Install tools: ?
- Others: ?

**Comment by andyzhangx** [comment]
this driver does not support creating a private dns zone in another subs, could you configure storage account with private dns zone, and then use following storage class:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
provisioner: file.csi.azure.com
parameters:
  storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
  server: accountname.privatelink.file.core.windows.net
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```
