### ISSUE TITLE
Output: mount: /var/lib/kubelet/pods/bdd06a44-ffb0-4a22-b212-c633bcb30299/volumes/kubernetes.io~csi/xxx-xx-xxxxx-azurefile-csi/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/xxx-xx-xxxxx-azurefile-csi/globalmount does not exist.

### ISSUE THREAD

**Issue by geraldnolan** [kubernetes-sigs/azurefile-csi-driver#831]
**What happened**:

After updating our AKS node pool to Kubernetes version 1.20.9, When deploying, we receive a pod in a pending state with the error:

Output: mount: /var/lib/kubelet/pods/bdd06a44-ffb0-4a22-b212-c633bcb30299/volumes/kubernetes.io~csi/xxx-xx-xxxxx-azurefile-csi/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/xxx-xx-xxxxx-azurefile-csi/globalmount does not exist.

I tried to upgrade to the latest version of azurefile-csi-driver:

Also, referencing these issues as well: #731 and #620

**What you expected to happen**:
Before upgrading to the version of Kubernetes we had not seen this issue.

**How to reproduce it**:
Scale nodes to create additional pods to be stuck in pending state. 

**Anything else we need to know?**:

```bash
kubectl get po -o wide -n kube-system | grep csi-azurefile-node
csi-azurefile-node-5tnd2                    3/3     Running   0          14d     10.0.12.99    aks-systempool-31452879-vmss00000f   <none>           <none>
csi-azurefile-node-62fsd                    3/3     Running   0          14d     10.0.13.191   aks-systempool-31452879-vmss00000g   <none>           <none>
csi-azurefile-node-kg85h                    3/3     Running   0          14d     10.0.12.228   aks-systempool-31452879-vmss00000b   <none>           <none>
csi-azurefile-node-mpj94                    3/3     Running   0          14d     10.0.12.100   aks-systempool-31452879-vmss00000l   <none>           <none>
csi-azurefile-node-mvm6w                    3/3     Running   0          14d     10.0.13.213   aks-systempool-31452879-vmss000009   <none>           <none>
csi-azurefile-node-td4qr                    3/3     Running   0          14d     10.0.14.176   aks-systempool-31452879-vmss00000i   <none>           <none>
csi-azurefile-node-xhr7c                    3/3     Running   0          14d     10.0.12.9     aks-systempool-31452879-vmss000008   <none>           <none>

```

**Environment**:
- CSI Driver version: mcr.microsoft.com/k8s/csi/azurefile-csi:v1.7.0
- Kubernetes version (use `kubectl `version`): Kubectl Client Version: v1.22.2, Kubectl Server Version: v1.20.9
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: Kubernetes version 1.20.9

**Comment by andyzhangx** [comment]
do you have two PVs that has same `volumeid`?

**Comment by geraldnolan** [comment]
I have two PV sharing the same **volumeHandle**.  (staging and production) I can't remember where I got the volumeHandle to be honest.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: xxx-xx-xxxxx-azurefile-csi
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 600Gi
  csi:
    driver: file.csi.azure.com
    nodeStageSecretRef:
      name: azure-csistorage-secret
      namespace: default
    volumeAttributes:
      resourceGroup: RG-XX-XX-XXX-XXXSTORAGE01
      shareName: xx-prod
      storageAccount: kubestorage
    volumeHandle: ebcf2da3-baae-421e-99bb-f44dd3224c4c
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - nosharesock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: xxxxx-azurefile-csi
  volumeMode: Filesystem
```

**old csi driver**: v1.5.0
