### ISSUE TITLE
file.csi.azure.com does not create storageaccount k8s secret automatically

### ISSUE THREAD

**Issue by Bananenbieger1234** [kubernetes-sigs/azurefile-csi-driver#845]
**What happened**:
I have a custom storageclass with provisioner "file.csi.azure.com" together with a configuration for my azure storageaccount.
The new csi provisioner does not create this secret, as a result, my services could not access the storage account due to mount failure.

**What you expected to happen**:
I expect the csi provisioner to create a k8s secret with the storageaccount credentials (like "kubernetes.io/azure-file" provisioner already did).
`azure-storage-account-xxx-secret`

**How to reproduce it**:

Create a custom storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-test
provisioner: file.csi.azure.com
parameters:
  resourceGroup: xxx
  secretNamespace: xxx
  storageAccount: xxx
reclaimPolicy: Delete
mountOptions:
  - gid=1001
  - nobrl
  - mfsymlinks
  - uid=1001
  - file_mode=0660
  - actimeo=30
  - dir_mode=0770
  - cache=strict
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Deploy a stateful service with a pvc that uses the custom storage class above.

**Anything else we need to know?**:

**Environment**:
Azure aks:
- CSI Driver version: I don't know where to get this from
- Kubernetes version (use `kubectl version`): 1.21.2
