### ISSUE TITLE
Volume metrics no longer available after update to version 1.9.0

### ISSUE THREAD

**Issue by florinherbert** [kubernetes-sigs/azurefile-csi-driver#904]
**What happened:**
After AKS updated the azurefile csi driver to version 1.9.0, metrics for volumes are no longer available (kubelet_volume_stats_capacity_bytes, kubelet_volume_stats_available_bytes, etc)

**What you expected to happen**:
Metrics to still be available

**How to reproduce it**:
We have prometheus installed in the cluster, and volume metrics are returned by this (default from helm) configuration:
```yaml
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: kubernetes-nodes
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics
    source_labels:
    - __meta_kubernetes_node_name
    target_label: __metrics_path__
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
```

**Anything else we need to know?**:
We assume the metrics disappeared because of this change: [feat: disable GET_VOLUME_STATS by default](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/846 )

We tried to set --enable-get-volume-stats=true to re-instate the capability, but it doesn't seem to work. I'm not a go programmer, but it seems to me that function [func NewDriver(options *DriverOptions) *Driver](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefile/azurefile.go#L208) doesn't copy the enableGetVolumeStats value.

**Environment**:
- CSI Driver version: 1.9.0
- Kubernetes version (use `kubectl version`): 1.22.4
- Others: AKS 1.22.4
