### ISSUE TITLE
fsType: ext4 does not work

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/azurefile-csi-driver#941]
**What happened**:
The CSI driver explicitly allows `fsType: ext4` in storage class parameters ([and other block volume fsTypes](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefile/azurefile.go#L156)) , however, it's not clear why. Mounting a volume with `fsType: ext4` fails with:

`Warning  FailedMount       100s (x9 over 3m51s)  kubelet            MountVolume.MountDevice failed for volume "pvc-7e760fb5-a5fb-46a2-82dd-d33929287dff" : rpc error: code = Internal desc = could not format "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-7e760fb5-a5fb-46a2-82dd-d33929287dff/globalmount" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-7e760fb5-a5fb-46a2-82dd-d33929287dff/proxy-mount/pvcd-7e760fb5-a5fb-46a2-82dd-d33929287dff.vhd"
`

**What you expected to happen**:
Volume creation with `fsType: ext4` should fail, AzureFile can't provide a volume with this filesystem. Similarly, `xfs`, `ext3` and `ext2` should fail too.

**How to reproduce it**:
Use this storage class, provision a PVC with it and use it in a Pod:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test
parameters:
  skuName: Standard_LRS
  fsType: ext4
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:  1.8.0
- Kubernetes version (use `kubectl version`): 1.23.3
