### ISSUE TITLE
can't use my own storage account which in another resourceGroup

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/azurefile-csi-driver#977]
**What happened**:

I want to use my own storage account which is in another resourse group to dynamic create pvs.
And I found some parameters [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md).
The follows are my yaml files.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azurefile-myown
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: RG-Name
  storageAccount: accountname
  shareName: sharename
  storeAccountKey: "true"
  secretName: azurefile-myown-secret
  secretNamespace: default
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict  # https://linux.die.net/man/8/mount.cifs
- nosharesock  # reduce probability of reconnect race
- actimeo=30  # reduce latency for metadata-heavy workload

---
apiVersion: v1
kind: Secret
metadata:
  name: azurefile-myown-secret
type: Opaque
data:
  azurestorageaccountname: somebase64accountname
  azurestorageaccountkey: somebase64accountkey

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-myown
  volumeMode: Filesystem
```

With these yaml files, when I use "kubectl describe pvc test-pvc" to check my pvc, the following are shown.

```
Warning  ProvisioningFailed    10s (x3 over 13s)  file.csi.azure.com_csi-azurefile-controller-xxxxxxxxxx-xxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  failed to provision volume with StorageClass "azurefile-myown": rpc error: code = Internal desc = storage.FileSharesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' with object id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/fileServices/shares/read' over scope '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/RG-Name/providers/Microsoft.Storage/storageAccounts/accountname/fileServices/default/shares/sharename' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

I also find that you(I mean this project, don't mind) provide another way to do what I want to. link [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account)

And I did this with following yaml files.

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azurefile-myown
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/provisioner-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict  # https://linux.die.net/man/8/mount.cifs
- nosharesock  # reduce probability of reconnect race
- actimeo=30  # reduce latency for metadata-heavy workload

---
apiVersion: v1
kind: Secret
metadata:
  name: azurefile-myown-secret
type: Opaque
data:
  azurestorageaccountname: somebase64accountname
  azurestorageaccountkey: somebase64accountkey

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-myown
  volumeMode: Filesystem
```

But it also occured an error with following info.

```
Warning  ProvisioningFailed    12s                file.csi.azure.com_csi-azurefile-controller-xxxxxxxxxx-xxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  failed to provision volume with StorageClass "azurefile-myown": rpc error: code = Internal desc = storage: service returned error: StatusCode=403, ErrorCode=403 This request is not authorized to perform this operation., ErrorMessage=no response body was available for error status code, RequestInitiated=Tue, 12 Apr 2022 01:23:45GMT, RequestId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, API Version=, QueryParameterName=, QueryParameterValue=
```

**What you expected to happen**:

Use my own storage account which is in another resourse group to dynamic create pvs.
I dont have permission to change IAM.

**How to reproduce it**:

Create a resource group named **RG-Name**.
Create a storage account named **accountname** in RG **RG-Name**.
Create a file share named **sharename** in storage account **accountname**.
Use the yaml file that I provided.

**Anything else we need to know?**:
Maybe I was in wrong usage. But my Azure MVP couldn't provide the resolution for me. So I asked here.

**Environment**:

- CSI Driver version: I don't know how to find it. I just updated my AKS cluster into 1.21, and it installed itself.
- Kubernetes version (use `kubectl version`): v1.21.9
- OS (e.g. from /etc/os-release): It is based on image AKSUbuntu-1804gen2containerd-2022.03.21.
- Kernel (e.g. `uname -a`): It is based on image AKSUbuntu-1804gen2containerd-2022.03.21.

**Comment by andyzhangx** [comment]
for the first usage, you should grant cluster identity permission to that resource group, follow example guide here: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-driver-on-aks.md#option2-enable-csi-driver-on-existing-cluster-with-version--121

for the second usage, is your storage account `Premium`? if yes, the minimum size should be 100GB

**Comment by OP-Kobayashi** [comment]
I do use an AKS cluster. LFS means large file shares.

**Comment by OP-Kobayashi** [comment]
I tried same account name and key with another usage [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-pvpvc), and it works.

**Comment by OP-Kobayashi** [comment]
I want to use the storage class method. Cloud you help me.

**Comment by andyzhangx** [comment]
> I want to use the storage class method. Cloud you help me.

@OP-Kobayashi you need to provide api-server address, otherwise it's quite hard to diagnostics. I would suggest creating an azure ticket.

**Comment by OP-Kobayashi** [comment]
api address? Do you mean endpoint?

**Comment by andyzhangx** [comment]
> api address? Do you mean endpoint?

aks api-server address, it's better filing an Azure support ticket.

**Comment by andyzhangx** [comment]
o, since you are in Azure China, try add `storageEndpointSuffix: "core.chinacloudapi.cn"` in parameters, e.g.
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azurefile-myown
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/provisioner-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  storageEndpointSuffix: "core.chinacloudapi.cn"
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict  # https://linux.die.net/man/8/mount.cifs
- nosharesock  # reduce probability of reconnect race
- actimeo=30  # reduce latency for metadata-heavy workload
```

**Comment by OP-Kobayashi** [comment]
It doesnot work with following info.
---
&nbsp; Warning&nbsp; ProvisioningFailed&nbsp; &nbsp; 18s&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; file.csi.azure.com_csi-azurefile-controller-57fc787986-gknch_1c50bc13-4ab0-4e22-a500-20ea4cb2c842&nbsp; failed to provision volume with StorageClass "azurefile-myown": rpc error: code = Internal desc = storage: service returned error: StatusCode=403, ErrorCode=403 This request is not authorized to perform this operation., ErrorMessage=no response body was available for error status code, RequestInitiated=Thu, 14 Apr 2022 09:19:39 GMT, RequestId=506e2e51-001a-002d-67e0-4f5719000000, API Version=, QueryParameterName=, QueryParameterValue=


I have tried&nbsp;following&nbsp;opintions&nbsp; with many combinations, but all useless.
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
&nbsp; name: azurefile-myown
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
&nbsp; #resourceGroup: KK-Azure-Tech-Shared
&nbsp; #storageAccount: kshared
&nbsp; #shareName: k8s-test
&nbsp; #location: china-east2
&nbsp; #server: kshared.file.core.chinacloudapi.cn
&nbsp; storageEndpointSuffix: "core.chinacloudapi.cn"
&nbsp; #storeAccountKey: "true"
&nbsp; #secretName: azurefile-myown-secret
&nbsp; #secretNamespace: default
&nbsp; csi.storage.k8s.io/provisioner-secret-name: azurefile-myown-secret
&nbsp; csi.storage.k8s.io/provisioner-secret-namespace: default
&nbsp; csi.storage.k8s.io/node-stage-secret-name: azurefile-myown-secret
&nbsp; csi.storage.k8s.io/node-stage-secret-namespace: default
&nbsp; csi.storage.k8s.io/controller-expand-secret-name: azurefile-myown-secret
&nbsp; csi.storage.k8s.io/controller-expand-secret-namespace: default
mountOptions:
&nbsp; - dir_mode=0777
&nbsp; - file_mode=0777
&nbsp; - uid=0
&nbsp; - gid=0
&nbsp; - mfsymlinks
&nbsp; - cache=strict&nbsp; # https://linux.die.net/man/8/mount.cifs
&nbsp; - nosharesock&nbsp; # reduce probability of reconnect race
&nbsp; - actimeo=30&nbsp; # reduce latency for metadata-heavy workload



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes-sigs/azurefile-csi-driver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes-sigs/azurefile-csi-driver] can't use my own storage account which in another resourceGroup (Issue #977)





 
o, since you are in Azure China, try add storageEndpointSuffix: "core.chinacloudapi.cn" in parameters, e.g.
 --- apiVersion: storage.k8s.io/v1 kind: StorageClass metadata: name: azurefile-myown provisioner: file.csi.azure.com allowVolumeExpansion: true parameters:   csi.storage.k8s.io/provisioner-secret-name: azurefile-myown-secret   csi.storage.k8s.io/provisioner-secret-namespace: default   csi.storage.k8s.io/node-stage-secret-name: azurefile-myown-secret   csi.storage.k8s.io/node-stage-secret-namespace: default   csi.storage.k8s.io/controller-expand-secret-name: azurefile-myown-secret   csi.storage.k8s.io/controller-expand-secret-namespace: default   storageEndpointSuffix: "core.chinacloudapi.cn" mountOptions: - dir_mode=0777 - file_mode=0777 - uid=0 - gid=0 - mfsymlinks - cache=strict  # https://linux.die.net/man/8/mount.cifs - nosharesock  # reduce probability of reconnect race - actimeo=30  # reduce latency for metadata-heavy workload

**Comment by OP-Kobayashi** [comment]
It doesnot work with following info.
```
  Warning  ProvisioningFailed    18s                file.csi.azure.com_csi-azurefile-controller-57fc787986-gknch_xxxxxxxxxx-xxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  failed to provision volume with StorageClass "azurefile-myown": rpc error: code = Internal desc = storage: service returned error: StatusCode=403, ErrorCode=403 This request is not authorized to perform this operation., ErrorMessage=no response body was available for error status code, RequestInitiated=Thu, 14 Apr 2022 09:19:39 GMT, RequestId=xxxxxxxxxx-xxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, API Version=, QueryParameterName=, QueryParameterValue=
```
I have tried following options  with many combinations, but all useless.
```yaml
apiVersion: [storage.k8s.io/v1](http://storage.k8s.io/v1)
kind: StorageClass
metadata:
  name: azurefile-myown
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  #resourceGroup: RG-Name
  #storageAccount: accountname
  #shareName: sharename
  #location: china-east2
  #server: accountname.file.core.chinacloudapi.cn
  storageEndpointSuffix: "core.chinacloudapi.cn"
  #storeAccountKey: "true"
  #secretName: azurefile-myown-secret
  #secretNamespace: default
  csi.storage.k8s.io/provisioner-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: azurefile-myown-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```
